--TVERTRAG
SELECT 
--'UPDATE VVERTRAG SET ZUSTAND=''F'' WHERE VERTR#=''' || VERTR# || ''' AND ZUSTAND=''' || ZUSTAND || '''',
VERTR#
,POLLFNR
,STADIUM
,ZUSTAND
FROM abs.TVERTRAG
where 1=1
--and STADIUM = '3'
--and ZUSTAND = 'A'
and POLLFNR in (
'004285817',
'004315274',
…)

--TTVERSVERTRAG
SELECT 
POLNR_VORSYS
v.POLLFNR
,vv.VERSV#
,vv.ZUSTAND 
FROM abs.TVERTRAG v
join abs.TVERSVERTRAG vv on v.VERTR# = vv.VERTR#
where 1=1
--and STADIUM = '3'
--and vv.ZUSTAND = 'A'
and POLLFNR in (
'004285817',
'004315274',
…)

--TVERTRZUS
SELECT 
'UPDATE VVERTRZUS set RAHMENVERTRNAME =''Migriert nach GBM am 24.02.2020'' || RAHMENVERTRNAME where VZUS# =''' || vz.VZUS# ||''''
,'UPDATE abs.TVERTRZUS set RAHMENVERTNAME = ''TEST '|| vz.RAHMENVERTRNAME || ' where VZUS# = '''|| vz.VZUS# ||''' and RAHMENVERTRNAME = ''' || vz.RAHMENVERTRNAME || ''';'  , vz.VZUS#, vz.RAHMENVERTRNAME 
--,v.POLLFNR
--,vz.RAHMENVERTRNAME
--,vz.VZUS#
FROM abs.TVERTRAG v
inner join abs.TVERTRZUS vz on v.VERTR# = vz.VERTR#
where 1=1
and v.STADIUM = '3' 
and POLLFNR in (
'004285817',
'004315274',
…)

--TGSCHFALL
SELECT 
'UPDATE VGSCHFALL SET GPSTATUS=''L'' WHERE GF#=''' || g.GF# || ''' AND GPSTATUS=''' || g.GPSTATUS|| ''''
,g.GF#
, g.GPSTATUS 
FROM abs.TVERTRAG v
join abs.TGSCHFALL g on v.GF# = g.GF#
where 1=1
and v.STADIUM = '3'
and v.POLLFNR in (
'003987076',
'005032597',
'000248700',

--VGSCHFALL QUELLE
Select 
'UPDATE VGSCHFALL SET QUELLE=''AG'' WHERE GF#=''' || tg.GF# || ''' AND QUELLE=''' || tg.QUELLE|| '''' as UpdateString
,vz.VZUS#,vz.POLNR_VORSYS, vt.VERTR#,vt.POLLFNR,vt.STADIUM,t1.DOMTEXT as VertStadium,vt.ZUSTAND, t11.DOMTEXT as VertStatus,tg.GF#, tg.FIRMA, tg.GPSTATUS, tg.QUELLE
from abs.TVERTRZUS vz
inner join abs.TVERTRAG vt on vz.VERTR# = vt.VERTR#
inner join abs.TGSCHFALL tg on vt.GF# = tg.GF#
inner join abs.TKZ_1 t1 on vt.STADIUM = t1.DOMWERT1 and t1.DOMNAME = 'VERTRAGSSTADIUM'
inner join abs.TKZ_1 t11 on vt.ZUSTAND = t11.DOMWERT1 and t11.DOMNAME = 'VERTRAGSZUSTAND'
and vz.POLNR_VORSYS in(
'6667863', '6640577')

--CISL report

SELECT *
FROM abs.TVERTRAG v
join abs.TGSCHFALL g on v.GF# = g.GF#
join abs.TVERTRZUS z on v.VERTR# = z.VERTR#
where g.QUELLE = 'MI'
and g.BEGINN > '2020-07-14'
and v.STADIUM = '3'
and v.FIRMA = 'DE'
--and v.WERBERNR in ...
--and v.FLOTTENNR in ...
--and v.ZUSTAND = 'A'
--and g.GPSTATUS = 'E'
--and g.ERSTELLUSER = 'IDE00000'
--and v.VERTRAUSFGRUND in ...
and v.VERTRART = 'LP'
--and v.ZAHLWEISE = 'E'
--and z.RAHMENVERTRNAME like ...
--and v.POLLFNR in ...
--and z.POLNR_VORSYS in ...
with ur


--revert TVERTRZUS

select 
VZUS#, RAHMENVERTRNAME 
--'UPDATE VVERTRZUS set RAHMENVERTRNAME =''Migriert nach GBM am 24.02.2020'' || RAHMENVERTRNAME where VZUS# =''' || vz.VZUS# ||''''
,'UPDATE VVERTRZUS set RAHMENVERTRNAME =  right(RAHMENVERTRNAME,length(RAHMENVERTRNAME)-32) where VZUS# =''' || vz.VZUS# ||'''' as updates
,right(vz.RAHMENVERTRNAME,length(vz.RAHMENVERTRNAME)-32) as correct
from abs.TVERTRZUS vz where vz.VZUS# in (
'78fdbc43-1ebe-11e7-8b81-005056871485',
'0a68d8d2-3e04-11e1-a1c3-9c8e99fbd1ec')

--xxx before TVERTZUS

SELECT 
'UPDATE VVERTRZUS set POLNR_VORSYS = ''XXX'|| TRIM(vz.POLNR_VORSYS) ||''', POLNR_VORSYSINT = ''XXX'|| TRIM(vz.POLNR_VORSYSINT) ||''' where POLNR_VORSYS = '''|| TRIM(vz.POLNR_VORSYS) ||''' and POLNR_VORSYSINT = '''|| TRIM(vz.POLNR_VORSYSINT) ||''' and VZUS# = '''|| TRIM(vz.VZUS#) ||''''
,v.POLLFNR
,v.VERTR#
,v.STADIUM
,vz.RAHMENVERTRNAME
,vz.VZUS#
,vz.POLNR_VORSYS
,vz.POLNR_VORSYSINT
FROM abs.TVERTRAG v
inner join abs.TVERTRZUS vz on v.VERTR# = vz.VERTR#
where 1=1
--and v.STADIUM = '3' 
and POLLFNR in (
'395820848',
'395821054',

-- xxx before TFRMNDKNR

select zz.*, length(zz.NewFRKNR) as Ncheck from (
SELECT 
'UPDATE VFREMDKNR set FRKNR = ''XXX'|| TRIM(f.FRKNR) ||''' where FRKNR = '''|| TRIM(f.FRKNR) ||''' and FRKNR# = '''|| TRIM(f.FRKNR#) ||'''' as updates
,f.* 
,'XXX'|| TRIM(f.FRKNR) as NewFRKNR
FROM abs.TVERTRAG v
--join abs.TVERTRZUS z on v.VERTR# = z.VERTR#
--join abs.TGSCHFALL g on v.GF# = g.GF#
join abs.TVNEHMER vn on v.VERTR# = vn.VERTR#
join abs.TFREMDKNR f on vn.PERS# = f.PERS#
where v.POLLFNR in (
'395820848',
'395821054')
)zz



--new APL DB2
SELECT l2.*
FROM abs.TVERTRAG v, abs.TVERSVERTRAG vv, abs.TPRODAUS p, abs.TPRODAUS_LEIART a --TMO1_ASSISSCHICHT a
, abs.TPA_LART_LIMDEF l
, abs.TMO1_PALARTLIMDEF l2
where v.vertr# = vv.vertr#
and vv.versv# = p.versv#
and p.pap# = a.pap#
and a.PAPLART# = l.PAPLART#
and l.PLLDEF# = l2.PLLDEF#
and v.pollfnr = '392741163'

SELECT
 V.FIRMA CONCAT TRIM(v.POLLFNR) AS "Policy"
,NVL(Z.PP_BEZ,'') AS "Package"
,TRIM(VV.SPARTE_EIGEN) AS "Class"
,TRIM(PB2.PBKBEZ) AS "Cover"
,TRIM(PB.PBKBEZ) AS "Sub Cover"
,A.*
,B.*
,C.*
FROM ABS.TVERTRAG V
INNER JOIN ABS.TVERSVERTRAG VV ON VV.VERTR# = V.VERTR#
LEFT JOIN ABS.TPRODPAKET_VV X ON X.VERSV# = VV.VERSV#
LEFT JOIN ABS.TPRODPAKET Z ON Z.PP# = X.PP#
INNER JOIN ABS.TPRODAUS P ON P.VERSV# = VV.VERSV#
INNER JOIN ABS.TPRODSCHABL PS ON PS.PSCHABL# = P.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB ON PB.PB# = PS.PB#
INNER JOIN ABS.TPRODSCHABL PS2 ON PS.UEB_PSCHABL# = PS2.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB2 ON PB2.PB# = PS2.PB#
LEFT JOIN ABS.TPRODAUS_LEIART A on P.PAP# = A.PAP#
LEFT JOIN ABS.TPA_LART_LIMDEF B on A.PAPLART# = B.PAPLART#
LEFT JOIN ABS.TMO1_PALARTLIMDEF C ON B.PLLDEF# = C.PLLDEF# 
WHERE V.POLLFNR IN ('393811979','393811983'
)
--ORDER BY V.POLLFNR, NVL(Z.PP_BEZ,''), TRIM(vv.SPARTE_EIGEN), TRIM(pb2.PBKBEZ), TRIM(pb.PBKBEZ);
UATTRV-21362

--CMC
WITH
EVENT_TREE (PRODUCT, CLASS_ID, CLASS_NAME, COVER_ID, COVER_NAME, SUB_COVER_ID, SUB_COVER_NAME, EB_TYPE, EB_ID, EB_NAME)AS(
    SELECT DISTINCT a.HSP_PRODBEZ,c.SPARTE_EIGEN, c.SP_PRODBEZ, e.PBKBEZ, e.PRODBAUBEZ,eb.PBKBEZ, eb.PRODBAUBEZ, 'EVENTS', g.SSP_KBEZ, g.SSP_BEZ
    FROM THSP_PRODUKT a
    JOIN TPBUENDBEST b ON (b.HSPP# = a.HSPP# AND b.VERBTYP = 'W')
    JOIN TSP_PRODUKT c ON c.SPP# = b.SPP# -- classes
    LEFT JOIN TPRODSCHABL d ON (d.SPP# = c.SPP# AND d.VERBTYP = 'W' AND d.UEB_PSCHABL# is null AND d.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN e ON (e.PB# = d.PB# AND e.BAUSTEINTYP = 'Z') -- covers
    LEFT JOIN TPRODSCHABL db ON (db.SPP# = c.SPP# AND db.UEB_PSCHABL# = d.PSCHABL# AND db.VERBTYP = 'W' AND db.UEB_PSCHABL# IS NOT NULL AND db.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN eb ON (eb.PB# = db.PB# AND eb.BAUSTEINTYP = 'R') -- sub-covers
    LEFT JOIN TPBDECKUNG f ON f.PB# = eb.PB#
    LEFT JOIN TSCHADENSPEZ g ON (g.SSP# = f.ART_SSP# AND g.SSP_TYP = 'ART') -- events
    JOIN TEART_DETAIL h ON (h.ART_SSP# = g.SSP# AND h.GILTBIS > CURRENT DATE)
    JOIN TEART_VORSCHRIFT i ON (i.EARTVOR# = h.EARTVOR#)
    JOIN TPROD_EART j ON (j.EARTVOR# = i.EARTVOR# AND j.SPP# = c.SPP# AND j.GILTBIS > CURRENT DATE)
),
BENEFIT_TREE (PRODUCT, CLASS_ID, CLASS_NAME, COVER_ID, COVER_NAME, SUB_COVER_ID, SUB_COVER_NAME, EB_TYPE, EB_ID, EB_NAME)
AS(
    SELECT DISTINCT a.HSP_PRODBEZ,c.SPARTE_EIGEN, c.SP_PRODBEZ, e.PBKBEZ, e.PRODBAUBEZ,eb.PBKBEZ, eb.PRODBAUBEZ,'BENEFITS', f.DOMWERT3, f.DOMTEXT
    FROM THSP_PRODUKT a
    JOIN TPBUENDBEST b ON (b.HSPP# = a.HSPP# AND b.VERBTYP = 'W')
    JOIN TSP_PRODUKT c ON c.SPP# = b.SPP# -- classes
    LEFT JOIN TPRODSCHABL d ON (d.SPP# = c.SPP# AND d.VERBTYP = 'W' AND d.UEB_PSCHABL# is null AND d.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN e ON (e.PB# = d.PB# AND e.BAUSTEINTYP = 'Z') -- covers
    LEFT JOIN TPRODSCHABL db ON (db.SPP# = c.SPP# AND db.UEB_PSCHABL# = d.PSCHABL# AND db.VERBTYP = 'W' AND db.UEB_PSCHABL# IS NOT NULL AND db.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN eb ON (eb.PB# = db.PB# AND eb.BAUSTEINTYP = 'R') -- sub-covers
    LEFT JOIN TMO1_PRODLEISTANG h ON (h.SPP# = c.SPP# AND h.PSCHABL# = db.PSCHABL# AND h.GILTBIS > CURRENT DATE)
    LEFT JOIN TKZ_3 f ON (f.DOMWERT3 = h.SACHGEBIET AND f.DOMNAME='SACHGEBIET' AND f.GILT_BIS > CURRENT DATE) -- benefits
)
SELECT * FROM (
    SELECT PRODUCT, CLASS_ID, CLASS_NAME, COVER_ID, COVER_NAME, SUB_COVER_ID, SUB_COVER_NAME, EB_TYPE, EB_ID, EB_NAME,
    CASE
        WHEN EB_TYPE = 'EVENTS' THEN TRIM(CLASS_ID) || '-' || TRIM(COVER_ID) || '-' || TRIM(SUB_COVER_ID) || '-E-' || TRIM(EB_ID)
        WHEN EB_TYPE = 'BENEFITS' THEN TRIM(CLASS_ID) || '-' || TRIM(COVER_ID) || '-' || TRIM(SUB_COVER_ID) || '-B-' || TRIM(EB_ID)
        ELSE 'UNKNOWN'
    END AS EB_CODE
    FROM (
            SELECT DISTINCT * FROM EVENT_TREE
            UNION ALL
            SELECT DISTINCT * FROM BENEFIT_TREE
    )
)
WHERE 1=1
AND PRODUCT LIKE '%(FoS)%' -- product filter
--AND CLASS_ID IN ('KG', 'FI') -- class filter
--AND COVER_ID IN ('DD0', 'DD1', 'DD2', 'DD3', 'DD4', 'DD5', '700') -- cover filter
--AND SUB_COVER_ID IN ('DDD01', 'DDD02', 'DDD03', 'DDD04', 'DDD05', 'M02022') -- sub-cover filter
--AND EB_CODE  IN ('AA-1100-110019-B-287')
--AND EB_TYPE = 'EVENTS'
--AND EB_TYPE = 'BENEFITS'
--AND EB_NAME IS NOT NULL
AND COVER_ID NOT LIKE 'IOB%' -- filter insured object
--AND COVER_ID NOT LIKE '%-DE%' -- filter main component
ORDER BY PRODUCT, CLASS_ID, COVER_ID, SUB_COVER_ID, EB_TYPE, EB_ID

--riskikoschl

SELECT * FROM abs.TPRODAUS where PAP# = 'b68e3d71-055b-11eb-9d96-00505699a57b'

SELECT * FROM abs.TPRODBAUSTEIN where PBLAUFNR = '15232'

SELECT * FROM abs.TTARIFRISIKOSCHL where PB# = '9ca297e1-d960-11e9-976f-901b0e1c0ce5'



select p.PAP#, t.TARRISIKOSCHL from abs.TPRODAUS p
left join abs.TPRODBAUSTEIN pr on p.PBLAUFNR = pr.PBLAUFNR
left join abs.TTARIFRISIKOSCHL t on pr.PB# = t.PB#
where p.PAP# in (
'0d0fb77f-33f5-11eb-8dbb-00505699bbae',
'0d13af25-33f5-11eb-8dbb-00505699bbae',
'0d14c096-33f5-11eb-8dbb-00505699bbae',
'0d1fe433-33f5-11eb-8dbb-00505699bbae',
'0d20a784-33f5-11eb-8dbb-00505699bbae',
'0d216ad5-33f5-11eb-8dbb-00505699bbae',
'0d22ca67-33f5-11eb-8dbb-00505699bbae',
'0d2366a8-33f5-11eb-8dbb-00505699bbae',
'0d45bbc7-33f5-11eb-8dbb-00505699bbae')


SELECT ABS.CREUUID(1) FROM ABS.TPRODAUS_LEIART limit 298
SELECT ABS.CREUUID(1) FROM ABS.TPA_LART_LIMDEF limit 298
SELECT ABS.CREUUID(1) FROM ABS.TMO1_PALARTLIMDEF limit 298

'||CHR(10)||'


select 
--'UPDATE VVERTRAG_GEN SET AINHALT=''2018-01-03'' WHERE VGEN#=''' || VGEN# || ''' AND AINHALT=''' || AINHALT || '''',
v.VERTR#, v.POLLFNR ,v.ZUSTAND, v.STADIUM, vg.VGEN#, vg.AINHALT from abs.TVERTRAG v
left join abs.TVERTRAG_GEN vg on v.VERTR# = vg.VERTR# and vg.ABEZ = 'AMBEFMIG'
where v.POLLFNR = '396053439' --('75981346-1fe3-11eb-a91f-00505699602f', '319146f8-f991-11ea-9031-00505699101e')



'3ccafe2d-395d-11eb-96db-005056997075'

select p.PAP#, t.TARRISIKOSCHL from abs.TPRODAUS p
left join abs.TPRODBAUSTEIN pr on p.PBLAUFNR = pr.PBLAUFNR
left join abs.TTARIFRISIKOSCHL t on pr.PB# = t.PB#
where p.PAP# in (
'3ccafe2d-395d-11eb-96db-005056997075')


--NS393816501



--extended new APL

WITH SUBCMC(POLICYNO,PACKAGENAME,CLASSCODE,CLASSNAME,COVERCODE,COVERNAME,SUBCOVERCODE,SUBCOVERNAME,EVENTCODE,EVENTNAME,BENEFITCODE,BENEFITNAME) AS (
SELECT
 V.FIRMA || TRIM(v.POLLFNR)
,NVL(Z.PP_BEZ,'')
,TRIM(C.SPARTE_EIGEN)
,C.SP_PRODBEZ
,TRIM(PB2.PBKBEZ)
,PB2.PRODBAUBEZ
,TRIM(PB1.PBKBEZ)
,PB1.PRODBAUBEZ
,EVD.SSP_KBEZ
,EVD.SSP_BESCHREIBUNG
,BE.SACHGEBIET
,BED.DOMTEXT
FROM ABS.TVERTRAG V
LEFT JOIN ABS.TVERSVERTRAG VV ON VV.VERTR# = V.VERTR#
LEFT JOIN ABS.TPRODPAKET_VV X ON X.VERSV# = VV.VERSV#
LEFT JOIN ABS.TPRODPAKET Z ON Z.PP# = X.PP#
INNER JOIN ABS.THSP_PRODUKT P ON V.HSPP# = P.HSPP#
INNER JOIN ABS.TPBUENDBEST PC ON P.HSPP# = PC.HSPP#
INNER JOIN ABS.TSP_PRODUKT C ON PC.SPP# = C.SPP#
INNER JOIN ABS.TPRODSCHABL PS1 ON C.SPP# = PS1.SPP#
INNER JOIN ABS.TPRODBAUSTEIN PB1 ON PS1.PB# = PB1.PB#
INNER JOIN ABS.TPRODSCHABL PS2 ON PS1.UEB_PSCHABL# = PS2.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB2 ON PS2.PB# = PB2.PB#
INNER JOIN ABS.TPBDECKUNG EV ON PB1.PB# = EV.PB#
INNER JOIN ABS.TSCHADENSPEZ EVD ON EV.ART_SSP# = EVD.SSP#
INNER JOIN ABS.TMO1_PRODLEISTANG BE ON PS1.PSCHABL# = BE.PSCHABL# AND C.SPP# = BE.SPP#
INNER JOIN ABS.TKZ_3 BED ON BED.DOMNAME = 'SACHGEBIET' AND BE.SACHGEBIET = BED.DOMWERT3
WHERE V.POLLFNR IN (
'393816501')
ORDER BY 1,2,3,5,7
WITH UR
)
,TEMP (POLICY,PACKAGE,CLASS, COVER, SUBCOVER
,PAPLART#, LART, TARRISIKOSCHL, ABHAENGIG,ABHGRUPPE,ANZEBENE,SORTIERUNG5, PAP#,SARTKBEZLISTE,SURSKBEZLISTE,LARTLISTE
,PLLDEF#,LIMITTYP,LIMITTYPDET,LIMITBETRAG,LIMITBETRAG2,LIMITANZ,LIMITPROZ,LIMITBEZUG,LIMITPERIODE,LIMREIHENFOLGE,PAPLART,LIMITBESCHR
,MO1_PLLDEF#,FREMDWAEHRUNG,KZBRUTTO,MO1_KZINLAND,MO1_LIMIT_DAYS,MO1_MIN_DIST,MO1_MAX_DIST,MO1_SENDCOSTEST,MO1_SENDMAXCOV,MO1_MAXDISTDELPROV,MO1_TIMETOSERVPROV,PLLDEF,MO1_DIST_BETWEEN
)as(
SELECT
 V.FIRMA CONCAT TRIM(v.POLLFNR) AS "Policy"
,NVL(Z.PP_BEZ,'') AS "Package"
,TRIM(VV.SPARTE_EIGEN) AS "Class"
,TRIM(PB2.PBKBEZ) AS "Cover"
,TRIM(PB.PBKBEZ) AS "Sub Cover"
,A.*
,B.*
,C.*
FROM ABS.TVERTRAG V
INNER JOIN ABS.TVERSVERTRAG VV ON VV.VERTR# = V.VERTR#
LEFT JOIN ABS.TPRODPAKET_VV X ON X.VERSV# = VV.VERSV#
LEFT JOIN ABS.TPRODPAKET Z ON Z.PP# = X.PP#
INNER JOIN ABS.TPRODAUS P ON P.VERSV# = VV.VERSV#
INNER JOIN ABS.TPRODSCHABL PS ON PS.PSCHABL# = P.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB ON PB.PB# = PS.PB#
INNER JOIN ABS.TPRODSCHABL PS2 ON PS.UEB_PSCHABL# = PS2.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB2 ON PB2.PB# = PS2.PB#
LEFT JOIN ABS.TPRODAUS_LEIART A on P.PAP# = A.PAP#
LEFT JOIN ABS.TPA_LART_LIMDEF B on A.PAPLART# = B.PAPLART#
LEFT JOIN ABS.TMO1_PALARTLIMDEF C ON B.PLLDEF# = C.PLLDEF# 
WHERE V.POLLFNR IN ('393816501')
)
Select t.*, d.CLASSNAME, d.COVERNAME, d.SUBCOVERNAME, d.EVENTNAME, d.BENEFITNAME from TEMP t
left join 
(SELECT DISTINCT POLICYNO ,PACKAGENAME ,CLASSCODE ,CLASSNAME ,COVERCODE ,COVERNAME ,SUBCOVERCODE ,SUBCOVERNAME ,EVENTCODE ,EVENTNAME ,BENEFITCODE ,BENEFITNAME  FROM SUBCMC
WHERE 1=0
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'CA' AND COVERCODE = 'R010' AND SUBCOVERCODE = 'R01001' AND EVENTCODE = 'XP017' AND BENEFITCODE = 'XM6')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01010' AND EVENTCODE = 'XP083' AND BENEFITCODE = 'X83')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01010' AND EVENTCODE = 'XP083' AND BENEFITCODE = 'XM2')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01010' AND EVENTCODE = 'XP116' AND BENEFITCODE = 'X83')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01010' AND EVENTCODE = 'XP116' AND BENEFITCODE = 'XM2')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01001' AND EVENTCODE = 'XP083' AND BENEFITCODE = 'X36')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01001' AND EVENTCODE = 'XP083' AND BENEFITCODE = 'YZ7')
OR (POLICYNO = 'NS393816501' AND PACKAGENAME = '' AND CLASSCODE = 'AA' AND COVERCODE = 'A010' AND SUBCOVERCODE = 'A01001' AND EVENTCODE = 'XP083' AND BENEFITCODE = 'XI6')
) d 
on t.POLICY = d.POLICYNO and t.CLASS = d.CLASSCODE and t.COVER = d.COVERCODE and t.SUBCOVER = d.SUBCOVERCODE and t.SARTKBEZLISTE = d.EVENTCODE and t.LARTLISTE = d.BENEFITCODE

--for CH
select abs.timestampuuid(g.GF#),  g.*, t.DOMTEXT from abs.TGSCHFALL g
left join abs.TKZ_1 t on g.GESCHFALL = t.DOMWERT1 and t.DOMNAME = 'GESCHAEFTSFALL'

'393779196'



Select
--DISTINCT
FIRMA,VERTRART,
CASE VERTRART
	WHEN 'GG' THEN 'MPOP! Multi-Package Open Policy'
	WHEN 'RA' THEN 'Master contract'
	WHEN 'GP' THEN 'Open Policy'
	ELSE 'ERROR'
END,
STADIUM
,v.FIRMA
,v.STADIUM
,v.POLLFNR
,v.HSP_PRODBEZ
,t1.DOMTEXT
from ABS.TVERTRAG V
inner join abs.TKZ_1 t1 on v.STADIUM = t1.DOMWERT1 and t1.DOMNAME = 'VERTRAGSSTADIUM'
WHERE V.POLLFNR IN (
'393817350',
'393817351',
'393817352',
'393817348',
'393816499',
'393816498',
'393818671'
)


--UK393817352 
Select
--DISTINCT
FIRMA,VERTRART,
CASE VERTRART
	WHEN 'GG' THEN 'MPOP! Multi-Package Open Policy'
	WHEN 'RA' THEN 'Master contract'
	WHEN 'GP' THEN 'Open Policy'
	ELSE 'ERROR'
END,
STADIUM
,v.FIRMA
,v.STADIUM
,v.POLLFNR
,v.HSP_PRODBEZ
,t1.DOMTEXT
from ABS.TVERTRAG V
inner join abs.TKZ_1 t1 on v.STADIUM = t1.DOMWERT1 and t1.DOMNAME = 'VERTRAGSSTADIUM'
WHERE V.POLLFNR IN (
'393817354',
'393818103',
'393817356'
)




Select
--DISTINCT
FIRMA,VERTRART,
CASE VERTRART
	WHEN 'GG' THEN 'MPOP! Multi-Package Open Policy'
	WHEN 'RA' THEN 'Master contract'
	WHEN 'GP' THEN 'Open Policy'
	ELSE 'ERROR'
END,
STADIUM
,v.FIRMA
,v.STADIUM
,v.POLLFNR
,v.HSP_PRODBEZ
,t1.DOMTEXT
from ABS.TVERTRAG V
inner join abs.TKZ_1 t1 on v.STADIUM = t1.DOMWERT1 and t1.DOMNAME = 'VERTRAGSSTADIUM'
WHERE V.POLLFNR IN (
'393816485',
'393816493',
'393818108',
'393818210',
'393818218',
'393818225')




SELECT
'DELETE ABS.TPA_LART_LIMDEF where PLLDEF# =''' || B.PLLDEF# || ''';'
FROM ABS.TVERTRAG V
INNER JOIN ABS.TVERSVERTRAG VV ON VV.VERTR# = V.VERTR#
LEFT JOIN ABS.TPRODPAKET_VV X ON X.VERSV# = VV.VERSV#
LEFT JOIN ABS.TPRODPAKET Z ON Z.PP# = X.PP#
INNER JOIN ABS.TPRODAUS P ON P.VERSV# = VV.VERSV#
INNER JOIN ABS.TPRODSCHABL PS ON PS.PSCHABL# = P.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB ON PB.PB# = PS.PB#
INNER JOIN ABS.TPRODSCHABL PS2 ON PS.UEB_PSCHABL# = PS2.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB2 ON PB2.PB# = PS2.PB#
LEFT JOIN ABS.TPRODAUS_LEIART A on P.PAP# = A.PAP#
LEFT JOIN ABS.TPA_LART_LIMDEF B on A.PAPLART# = B.PAPLART#
LEFT JOIN ABS.TMO1_PALARTLIMDEF C ON B.PLLDEF# = C.PLLDEF# 
WHERE V.POLLFNR IN ('393819823'
) and B.PLLDEF# is not null


SELECT
'DELETE ABS.TPRODAUS_LEIART where PAPLART# =''' || A.PAPLART# || ''';'
FROM ABS.TVERTRAG V
INNER JOIN ABS.TVERSVERTRAG VV ON VV.VERTR# = V.VERTR#
LEFT JOIN ABS.TPRODPAKET_VV X ON X.VERSV# = VV.VERSV#
LEFT JOIN ABS.TPRODPAKET Z ON Z.PP# = X.PP#
INNER JOIN ABS.TPRODAUS P ON P.VERSV# = VV.VERSV#
INNER JOIN ABS.TPRODSCHABL PS ON PS.PSCHABL# = P.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB ON PB.PB# = PS.PB#
INNER JOIN ABS.TPRODSCHABL PS2 ON PS.UEB_PSCHABL# = PS2.PSCHABL#
INNER JOIN ABS.TPRODBAUSTEIN PB2 ON PB2.PB# = PS2.PB#
LEFT JOIN ABS.TPRODAUS_LEIART A on P.PAP# = A.PAP#
LEFT JOIN ABS.TPA_LART_LIMDEF B on A.PAPLART# = B.PAPLART#
LEFT JOIN ABS.TMO1_PALARTLIMDEF C ON B.PLLDEF# = C.PLLDEF# 
WHERE V.POLLFNR IN ('393819823'
) --and B.PLLDEF# is not null



select 
a.JP#_MUTTER, count(a.JP#_TOCHTER) as fff, c.KUNDENNR
from 
abs.TKONZMITGL a
inner join abs.TJURPERS b on a.JP#_MUTTER = b.JP#
inner join abs.TPERSON c on b.PERS# = c.PERS#
group by a.JP#_MUTTER, c.KUNDENNR order by 2 desc
--
WITH
BPS (CusID) AS (
SELECT distinct PER.KUNDENNR
                FROM ABS.TPERSON PER
                INNER JOIN ABS.TJURPERS JUR ON PER.PERS# = JUR.PERS#
                INNER JOIN ABS.TGBPARTNER GBP on PER.PERS# = GBP.PERS#
                INNER JOIN ABS.TGBP_SACHGEBIET SACH on GBP.GBP# = SACH.GBP#
                INNER JOIN ABS.TGSCHFALL TGS on PER.GF# = TGS.GF#
where 1=1
and GBP.KZPARTNER_STATUS ='A'
--and TGS.FIRMA in ('DE','DS')
)
SELECT g.FIRMA, count(*)
FROM ABS.TPERSON p
join BPS ON p.KUNDENNR = BPS.CusID
--join abs.TJURPERS j on p.PERS# = j.PERS#
join abs.TGSCHFALL g on p.GF# = g.GF#
GROUP by g.FIRMA


select abs.timestampuuid(tr.GBPTG#) as a, tr.*, tar.*, tal.*, tpr.* from ABS.TGBPTARGR tr
left join ABS.TGBPTARZUORD t on tr.GBPTG# = t.GBPTG#
left join ABS.TGBP_TARIF tar on t.GBPTAR# = tar.GBPTAR#
left join abs.TGBPLEIST tal on tar.GBPTAR# = tal.GBPTAR#
left join abs.TGBPLEIPREIS tpr on tal.GBPLEI# = tpr.GBPLEI#
left join abs.TGBPLEIPREIS_DET
where tr.TARGRBEZ like 'LKO200121 TG'


--person hierarchy

Select f.FRKNR, p.KUNDENNR, p.PERS#, j.FIRMENNAME, k.JP#_TOCHTER as LL, j1.FIRMENNAME, p1.KUNDENNR, f1.FRKNR --, GBP#  
from abs.TPERSON p
left join abs.TFREMDKNR f on p.PERS# = f.PERS#
left join abs.TJURPERS j on p.PERS# = j.PERS#
inner join abs.TKONZMITGL k on j.JP# = k.JP#_MUTTER
inner join abs.TJURPERS j1 on k.JP#_TOCHTER = j1.JP#
inner join abs.TPERSON p1 on j1.PERS# = p1.PERS#
inner join abs.TFREMDKNR f1 on p1.PERS# = f1.PERS#
--inner join abs.TGBPARTNER g on p.PERS# = g.PERS#
--inner join ABS.TGBP_NETZWERKZUORD n on g.GBP# = n.GBP#
where f.FRKNR in(
--'P10877P9',
--'P53786P9',
'P118049P9')

--contract with BI activites
select  abs.timestampuuid(v.VERTR#) as tme,v.VERTR#, v.FIRMA, v.HSP_EIGEN, v.POLLFNR, v.STADIUM, v.ZUSTAND
,g.*
,t.DOMTEXT
from abs.TVERTRAG v
inner join abs.TGSCHFAKT g on v.GF# = g.GF#
left join abs.TKZ_5 t on g.GFAKTIVITAET = t.DOMWERT5 and t.DOMNAME = 'GSCHFALLAKTIVITAET'
where v.POLLFNR = '396462923' 

--external product code check

SELECT * FROM TVERTRAG a
inner join TVERTRAG_GEN b on a.VERTR# = b.VERTR# and b.ABEZ = 'PRODCODE'
where b.AINHALT = 'B2CLTRASSLIGCV'

--lokation
select DISTINCT
ma.userid,
stelle.STELLEKURZBEZ,
--stelle.STELLENBEZ,
lokation.LOKNAME,
lokation.LOKKURZNAME,
mapos.MAPOSART
--rights.AP#,
from TMITARBEITER_DEF ma -- users
join tmapos mapos on ma.MA# = mapos.MA# -- combination of users & combination of roles & teams
join TSTELLENLOK stelleLok on mapos.STLOK# = stelleLok.STLOK# -- combination of role & team
join TSTELLE stelle on stelle.ST# = stelleLok.ST# -- roles
join TLOKATION lokation on stelleLok.LOKATION# = lokation.LOKATION# -- locations
where ma.USERID like 'IDE%'




select tabschema concat '.' concat tabname as table,
colname as column_name,
cast(default as varchar(20000)) as default_value
from syscat.columns
where tabschema not like 'SYS%'
and default is not 
null and tabname like 'TGBP_GEBIETZUORD%'
order by tabschema, tabname, colname

--- new SR
with
stmts(GFAKTIVITAET, GF#, STMT) as (
SELECT 
'VERAE'
,gf.GF#
,'UPDATE ABS.TVERTRZUS SET POLNR_VORSYS = ''XXX'|| TRIM(vz.POLNR_VORSYS) ||''', POLNR_VORSYSINT = ''XXX'|| TRIM(vz.POLNR_VORSYSINT) ||''' WHERE POLNR_VORSYS = '''|| TRIM(vz.POLNR_VORSYS) ||''' AND POLNR_VORSYSINT = '''|| TRIM(vz.POLNR_VORSYSINT) ||''' AND VZUS# = '''|| TRIM(vz.VZUS#) ||''';'
--,v.POLLFNR
--,v.VERTR#
--,v.STADIUM
--,vz.RAHMENVERTRNAME
--,vz.VZUS#
--,vz.POLNR_VORSYS
--,vz.POLNR_VORSYSINT
--,gf.GF#
FROM abs.TVERTRAG v
inner join abs.TVERTRZUS vz on v.VERTR# = vz.VERTR#
inner join abs.TGSCHFALL gf on v.GF# = gf.GF#
where 1=1
--and v.STADIUM = '3' 
and POLLFNR in (
'396045786',
'396053509',
'396045655')
),
ranked as (
select GFAKTIVITAET, GF#, STMT, dense_rank() over (order by gf#, GFAKTIVITAET) rk , row_number() over (partition by gf#, GFAKTIVITAET order by stmt) rn from stmts 
),
stacked as (
select 'C_GFAKT=' || GFAKTIVITAET stmt, rk, 1 rs from ranked where rn=1
union all
select 'C_GF#=' || GF# stmt, rk, 2 rs from ranked where rn=1
union all
select stmt, rk, rn+2 rs from ranked
order by rk, rs
)
SELECT stmt FROM stacked order by rk, rs


select abs.timestampuuid(tr.GBPTG#) as DATEADD, tr.*, tar.*, tal.*, tm.* from ABS.TGBPTARGR tr
inner join ABS.TGBPTARZUORD t on tr.GBPTG# = t.GBPTG#
inner join ABS.TGBP_TARIF tar on t.GBPTAR# = tar.GBPTAR#
inner join abs.TGBPLEIST tal on tar.GBPTAR# = tal.GBPTAR#
left join abs.TMO1_GBPLEIST tm on tal.GBPLEI# = tm.GBPLEI#
where tr.TARGRBEZ like 'T06%Agosport%'

--at least one is A01
with mytable (aa,bb) as (
select   p.PERS#, LISTAGG(CAST(TRIM(bp.GBPART) AS CLOB),';') from 
abs.TPERSON p
inner join abs.TJURPERS j on p.PERS# = j.PERS#
inner join abs.TGSCHFALL g on p.GF# = g.GF#
inner join abs.TFREMDKNR f on p.PERS# = f.PERS#
inner join abs.TGBPARTNER bp on p.PERS# = bp.PERS#
where f.FRKNR in ('0013778-196',
'0013792-196',
'0026509-196',
'0026512-196',
'0061225-196',
'0045353-196',
'0000244-188')
group by p.PERS#
) select * from mytable where BB like '%A01%'

--new CMC
set schema abs

WITH
EVENT_TREE (PRODUCT, CLASS_ID, CLASS_NAME, COVER_ID, COVER_NAME, SUB_COVER_ID, SUB_COVER_NAME, EB_TYPE, EB_ID, EB_NAME)AS(
    SELECT DISTINCT a.HSP_PRODBEZ,c.SPARTE_EIGEN, c.SP_PRODBEZ, e.PBKBEZ, e.PRODBAUBEZ,eb.PBKBEZ, eb.PRODBAUBEZ, 'EVENTS', g.SSP_KBEZ, g.SSP_BEZ
    FROM THSP_PRODUKT a
    JOIN TPBUENDBEST b ON (b.HSPP# = a.HSPP# AND b.VERBTYP = 'W')
    JOIN TSP_PRODUKT c ON c.SPP# = b.SPP# -- classes
    LEFT JOIN TPRODSCHABL d ON (d.SPP# = c.SPP# AND d.VERBTYP = 'W' AND d.UEB_PSCHABL# is null AND d.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN e ON (e.PB# = d.PB# AND e.BAUSTEINTYP = 'Z') -- covers
    LEFT JOIN TPRODSCHABL db ON (db.SPP# = c.SPP# AND db.UEB_PSCHABL# = d.PSCHABL# AND db.VERBTYP = 'W' AND db.UEB_PSCHABL# IS NOT NULL AND db.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN eb ON (eb.PB# = db.PB# AND eb.BAUSTEINTYP = 'R') -- sub-covers
    LEFT JOIN TPBDECKUNG f ON f.PB# = eb.PB#
    LEFT JOIN TSCHADENSPEZ g ON (g.SSP# = f.ART_SSP# AND g.SSP_TYP = 'ART') -- events
    JOIN TEART_DETAIL h ON (h.ART_SSP# = g.SSP# AND h.GILTBIS > CURRENT DATE)
    JOIN TEART_VORSCHRIFT i ON (i.EARTVOR# = h.EARTVOR#)
    JOIN TPROD_EART j ON (j.EARTVOR# = i.EARTVOR# AND j.SPP# = c.SPP# AND j.GILTBIS > CURRENT DATE)
),
BENEFIT_TREE (PRODUCT, CLASS_ID, CLASS_NAME, COVER_ID, COVER_NAME, SUB_COVER_ID, SUB_COVER_NAME, EB_TYPE, EB_ID, EB_NAME)
AS(
    SELECT DISTINCT a.HSP_PRODBEZ,c.SPARTE_EIGEN, c.SP_PRODBEZ, e.PBKBEZ, e.PRODBAUBEZ,eb.PBKBEZ, eb.PRODBAUBEZ,'BENEFITS', f.DOMWERT3, f.DOMTEXT
    FROM THSP_PRODUKT a
    JOIN TPBUENDBEST b ON (b.HSPP# = a.HSPP# AND b.VERBTYP = 'W')
    JOIN TSP_PRODUKT c ON c.SPP# = b.SPP# -- classes
    LEFT JOIN TPRODSCHABL d ON (d.SPP# = c.SPP# AND d.VERBTYP = 'W' AND d.UEB_PSCHABL# is null AND d.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN e ON (e.PB# = d.PB# AND e.BAUSTEINTYP = 'Z') -- covers
    LEFT JOIN TPRODSCHABL db ON (db.SPP# = c.SPP# AND db.UEB_PSCHABL# = d.PSCHABL# AND db.VERBTYP = 'W' AND db.UEB_PSCHABL# IS NOT NULL AND db.GILTBIS > CURRENT DATE)
    LEFT JOIN TPRODBAUSTEIN eb ON (eb.PB# = db.PB# AND eb.BAUSTEINTYP = 'R') -- sub-covers
    LEFT JOIN TPROD_LEISTANG  h ON (h.SPP# = c.SPP# AND h.PSCHABL# = db.PSCHABL# AND h.GILTBIS > CURRENT DATE)
    LEFT JOIN TKZ_3 f ON (f.DOMWERT3 = h.LART AND f.DOMNAME='SACHGEBIET' AND f.GILT_BIS > CURRENT DATE) -- benefits
)
SELECT * FROM (
    SELECT PRODUCT, CLASS_ID, CLASS_NAME, COVER_ID, COVER_NAME, SUB_COVER_ID, SUB_COVER_NAME, EB_TYPE, EB_ID, EB_NAME,
    CASE
        WHEN EB_TYPE = 'EVENTS' THEN TRIM(CLASS_ID) || '-' || TRIM(COVER_ID) || '-' || TRIM(SUB_COVER_ID) || '-E-' || TRIM(EB_ID)
        WHEN EB_TYPE = 'BENEFITS' THEN TRIM(CLASS_ID) || '-' || TRIM(COVER_ID) || '-' || TRIM(SUB_COVER_ID) || '-B-' || TRIM(EB_ID)
        ELSE 'UNKNOWN'
    END AS EB_CODE
    FROM (
            SELECT DISTINCT * FROM EVENT_TREE
            UNION ALL
            SELECT DISTINCT * FROM BENEFIT_TREE
    )
)
WHERE 1=1
AND PRODUCT = 'Freedom of Establishment (FoE) FR V09' -- product filter
AND CLASS_ID IN ('CG') -- class filter
--AND COVER_ID IN ('DD0', 'DD1', 'DD2', 'DD3', 'DD4', 'DD5', '700') -- cover filter
AND SUB_COVER_ID IN ('M03009') -- sub-cover filter
--AND EB_CODE  IN ('AA-1100-110019-B-287')
--AND EB_TYPE = 'EVENTS'
--AND EB_TYPE = 'BENEFITS'
--AND EB_NAME IS NOT NULL
AND COVER_ID NOT LIKE 'IOB%' -- filter insured object
--AND COVER_ID NOT LIKE '%-DE%' -- filter main component
ORDER BY PRODUCT, CLASS_ID, COVER_ID, SUB_COVER_ID, EB_TYPE, EB_ID

---

AP to AGA  M07 - AO3

select 
case when ta.AM# is null then
'INSERT INTO ABS.TAGENTMANAGER (AM#,BETREUER,MANAGEDCOMACC,BETRPROZ,KZBETRPROVART,GILTAB,GILTBIS, VERM#) VALUES ('''||ABS.CREUUID(1)||''','''||pr.WERBERNR||''','''',0,'''','''||current date||''',''9999-12-31'','''||m.VERM#||''');'
else '' end as INSERTS
,
p.*, a.*, k.*, pr.*, m.*, ta.*
from abs.TPERSON p
inner join abs.TADRESSE a on p.PERS# = a.PERS#
inner join abs.TKUNDENKONTO k on a.ADR# = k.ADR#
inner join abs.TPROVKONTO pr on k.KK# = pr.EXK_KK#
inner join abs.TVERMITTLER m on pr.VERM# = m.VERM#
left join  abs.TAGENTMANAGER ta on m.VERM# = ta.VERM#
where p.KUNDENNR in ('1024437', '1025994')

---

SELECT right(current date,2)||'.'||left(right(current date,5),2)||'.'||left(current date,4) FROM sysibm.sysdummy1 

SELECT current date FROM sysibm.sysdummy1 

SELECT trim(VARCHAR_FORMAT(CURRENT DATE, 'DD.MM.YYYY'))
FROM SYSIBM.SYSDUMMY1

---

select 'DPMHA' as ENV, POLLFNR from DPMHA.abs.TVERTRAG where POLLFNR in ('399714319','393950176') and STADIUM = '2'
union all
select 'DTMHA' as ENV, POLLFNR from DTMHA93.abs.TVERTRAG where POLLFNR in ('399714319','393950176')and STADIUM = '2'

--free up werebernr
with myTable (WB, WERBERNR, KZFREI, WERBERNRcheck) as (
SELECT w.*, p.WERBERNR FROM abs.TWERBERNR w
left join abs.TPROVKONTO p on w.WERBERNR = p.WERBERNR where p.WERBERNR is null and w.KZFREI = 'N'
--SELECT * FROM abs.TKKONTONR
) select 
mt.*
,'UPDATE ABS.TWERBERNR SET KZFREI = ''J'' WHERE WB# = '''||mt.WB||'''; ' 
from myTable mt

--

select p.PERS#, p.KUNDENNR, j.FIRMENNAME, f.FRKNR, g.BEGINN, g.GF#, a.ADR#, k.KK#
, p.PKTO#
from 
abs.TPERSON p
inner join abs.TJURPERS j on p.PERS# = j.PERS#
inner join abs.TGSCHFALL g on p.GF# = g.GF#
inner join abs.TFREMDKNR f on p.PERS# = f.PERS#
inner join abs.TADRESSE a on p.PERS# = a.PERS#
inner join abs.TKUNDENKONTO k on a.ADR# = k.ADR#
left join abs.TPROVKONTO p on k.KK# = p.EXK_KK#
where f.FRKNR = ('LK220302CZT1')


Select * FROM THSP_PRODUKT a
JOIN TPBUENDBEST b ON (b.HSPP# = a.HSPP# AND b.VERBTYP = 'W')
JOIN TSP_PRODUKT c ON c.SPP# = b.SPP#
LEFT JOIN TPRODSCHABL d ON d.SPP# = c.SPP#
LEFT JOIN TPRODBAUSTEIN e ON e.PB# = d.PB#
where a.HSP_PRODBEZ = 'Freedom of Establishment (FoE) OE V09' and e.PBLAUFNR in ('17781','17856')

--cartezjan nowy
SELECT pl.DOMBDET#, pl.DOMWBEZ_LISTE,pl.DOMWLISTE, right(BEN.BENEFIT,2)
FROM TDOMBEZUGDET pl
JOIN XMLTABLE (
   'for $id in tokenize($s, ",") return <i>{string($id)}</i>' PASSING pl.DOMWBEZ_LISTE AS "s"
   COLUMNS BENEFIT VARCHAR(20) PATH '.' ) AS BEN ON 1=1
where pl.DOMBDET# in ('dec3b56a-3816-11e8-a46b-00505687148e')
union all
SELECT pl.DOMBDET#, pl.DOMWBEZ_LISTE,pl.DOMWLISTE, right(BEN.BENEFIT,2)
FROM TDOMBEZUGDET pl
JOIN XMLTABLE (
   'for $id in tokenize($s, ",") return <i>{string($id)}</i>' PASSING pl.DOMWBEZ_LISTE AS "s"
   COLUMNS BENEFIT VARCHAR(20) PATH '.' ) AS BEN ON 1=1
where pl.DOMBDET# in ('808caf26-8f3d-11e7-ad88-5627ed2981a4')

-- zapytania online

SELECT abs.timestampuuid(t.STMT#), t.* FROM abs.TSTMT_ONLINE t  limit 10

-- GFM management
select * from babs.TDBBERBESCHR where TABLE_NAME = 'TVERTRZUS'

--FR Travel extraction

SQLs:

SELECT v.VERTR#, v.FIRMA || v.POLLFNR as VERTRAG, z.POLNR_VORSYS, b.FIRMA || b.POLLFNR as RAHMENVERTAG, z2.RAHMENVERTRNAME
, v.WERBERNR, p0.KUNDENNR, j0.FIRMENNAME
, v.VERTRART, v.ZAHLWEISE, v.INKASSOART, v.STADIUM, v.ZUSTAND, v.KONTOSTATUS, v.SALDO, v.VERTRAUSFGRUND
, g.BEGINN, g.AENDZP, g.QUELLE, v.BEGDAT, v.WIRKBEGDAT, v.ABLDAT, v.HPTFLLG
, gen7.AINHALT as INTPRCOD, gen8.AINHALT as EINTPCOD, gen9.AINHALT as EPRODCOD
, genx.AINHALT as BPRAEMIE, gen3.AINHALT as EPRAEMIE, gen5.AINHALT as KPRAEMIE
FROM abs.TVERTRAG v
join abs.TGSCHFALL g on v.GF# = g.GF#
join abs.TVERTRZUS z on v.VERTR# = z.VERTR#
join abs.TVERTRBEZUG b on v.VERTR# = b.VERTR#
left join abs.TVERTRAG v2 on b.POLLFNR = v2.POLLFNR and v2.STADIUM = '3'
left join abs.TVERTRZUS z2 on v2.VERTR# = z2.VERTR#
left join abs.TVERTRAG_GEN genx on v.VERTR# = genx.VERTR# and genx.ABEZ = 'BPRAEMIE'
left join abs.TVERTRAG_GEN gen3 on v.VERTR# = gen3.VERTR# and gen3.ABEZ = 'EPRAEMIE'
left join abs.TVERTRAG_GEN gen5 on v.VERTR# = gen5.VERTR# and gen5.ABEZ = 'KPRAEMIE'
left join abs.TVERTRAG_GEN gen7 on v.VERTR# = gen7.VERTR# and gen7.ABEZ = 'INTPRCOD'
left join abs.TVERTRAG_GEN gen8 on v.VERTR# = gen8.VERTR# and gen8.ABEZ = 'EINTPCOD'
left join abs.TVERTRAG_GEN gen9 on v.VERTR# = gen9.VERTR# and gen9.ABEZ = 'EPRODCOD'
              left join abs.TPROVKONTO pk on v.WERBERNR = pk.WERBERNR
              left join abs.TVERMITTLER vm on pk.VERM# = vm.VERM#
              left join abs.TMITARBEITER ma on vm.MA# = ma.MA#
              left join abs.TADRESSE a0 on ma.ADR# = a0.ADR#
              left join abs.TPERSON p0 on a0.PERS# = p0.PERS#
              left join abs.TJURPERS j0 on p0.PERS# = j0.PERS#
where v.STADIUM = '3'
and v.VERTRART = 'E'
and v.ZUSTAND = 'A'
and v.ZAHLWEISE = 'M'
--and v.KONTOSTATUS = '0'
--and v.SALDO = 0
with ur

SELECT
v.FIRMA || v.POLLFNR as VERTRAG --, v.WERBERNR
, bb.*
FROM abs.TVERTRAG v 
join abs.TBUBASIS bb on bb.KONTO# = v.VERTR#
where v.STADIUM = '3'
and v.VERTRART = 'E'
and v.ZUSTAND = 'A'
and v.ZAHLWEISE = 'M'
--and v.KONTOSTATUS = '0'
--and v.SALDO = 0
and bb.VERRMONAT >= '2023-01-01'
with ur

--PPL CHECK
Select abs.timestampuuid(v.VERTR#),v.*,g.* from abs.TVERTRAG v
inner join abs.TGSCHFALL g on v.GF# = g.GF#
where
1=1
and v.STADIUM = '2'
and v.FIRMA = 'HS'
and g.QUELLE = 'MI'
and g.GESCHFALL = 'V'
and g.GPSTATUS = 'D'


WITH inpTable(POLNR_VORSYS, BEGDAT) as (
SELECT 'B2CFR1000021960','2016-02-11' FROM SYSIBM.DUAL
),
contractTable (POLNR_VORSYS, BEGDAT_NEW, VERTR# ,POLLFNR, BEGDAT, STADIUM, ZUSTAND, GF#) as (
Select 
it.POLNR_VORSYS,it.BEGDAT, v.VERTR#, v.POLLFNR, v.BEGDAT, v.STADIUM, v.ZUSTAND, g.GF# 
from inpTable it
inner join ABS.TVERTRZUS vz on it.POLNR_VORSYS = vz.POLNR_VORSYSINT
inner join abs.TVERTRAG v on vz.VERTR# = v.VERTR#
inner join abs.TGSCHFALL g on v.GF# = g.GF#
)
Select ct.*,
'UPDATE ABS.TVERTRAG SET =''F'' WHERE VERTR#=''' || VERTR# || ''' AND ZUSTAND=''' || ZUSTAND || '''',

--set queries for assingment check

select * from abs.TMO1_EXTPRODCODE where MO1_PRODCODE = '023_MT_Y_Comprehensive'

select distinct FIRMA, POLLFNR from abs.TVERTRAG v
inner join abs.TVERTRAG_GEN vg on v.VERTR# = vg.VERTR# and vg.ABEZ = 'PRODCODE'
where vg.AINHALT = '023_MT_Y_Comprehensive'

select p.PERS#, p.KUNDENNR, j.FIRMENNAME, f.FRKNR from 
abs.TFREMDKNR f
inner join abs.TPERSON p on f.PERS# = p.PERS#
inner join abs.TJURPERS j on p.PERS# = j.PERS#
where 
f.FRKNR = '9TC347' 
and f.FRKNR_ART = 'FA2'

Select v.POLLFNR, p.KUNDENNR, j.FIRMENNAME, f.FRKNR from abs.TVERTRAG v
inner join abs.TRAZUORD r on v.POLLFNR = r.POLLFNR
inner join abs.TJURPERS j on r.JP# = j.JP#
inner join abs.TPERSON p on p.PERS# = j.PERS#
inner join abs.TFREMDKNR f on p.PERS# = f.PERS# and f.FRKNR_ART = 'FA2'
where 
1=1
and v.POLLFNR = '394264586'
and v.STADIUM = 3
--and f.FRKNR = '9TC347'


select p.PERS#, p.KUNDENNR, j.FIRMENNAME, f.FRKNR, fl.FLOTTENNR, fl.FLOTTENBEM, fl.FLOTTENVEREINB from 
abs.TFREMDKNR f
inner join abs.TPERSON p on f.PERS# = p.PERS#
inner join abs.TJURPERS j on p.PERS# = j.PERS#
inner join abs.TFLOTTE fl on j.JP# = fl.JP#
where 
f.FRKNR = '9TC347' 
and f.FRKNR_ART = 'FA2'

select * from abs.TRAZUORD where FLOTTENNR in ('653440','653441')

SELECT --*
p.KUNDENNR, j.FIRMENNAME, f.FRKNR
--, g.BEGINN
, g.ERSTELLUSER
,fl.FLOTTENNR, fl.FLOTTENVEREINB,fl.FLOTTENBEM, fl.VEREINBEGINN, fl.GILTBIS
,r.RAZINKRAFTDAT, r.RAZAUSKRAFTDAT, r.RAZVERKAUFSENDE
,v.POLLFNR, v.VERTRART, v.ZUSTAND, v.ZAHLWEISE, v.BEGDAT, v.WIRKBEGDAT, v.ABLDAT
,v.HSP_PRODBEZ, vg.AINHALT
FROM abs.TPERSON p
join abs.TGSCHFALL g on p.GF# = g.GF#
join abs.TJURPERS j on p.PERS# = j.PERS#
join abs.TFREMDKNR f on p.PERS# = f.PERS# and f.FRKNR_ART = 'FA2'
join abs.TFLOTTE fl on j.JP# = fl.JP#
join abs.TRAZUORD r on fl.FLOTTENNR = r.FLOTTENNR
join abs.TVERTRAG v on r.POLLFNR = v.POLLFNR and v.STADIUM = '3'
left join abs.TVERTRAG_GEN vg on v.VERTR# = vg.VERTR# and vg.ABEZ = 'PRODCODE'
where
1=1
and g.FIRMA = 'NL'
--and f.FRKNR = 'DZA300'
with ur

--
select * from abs.TDEFGENATTR


--
with root as (
SELECT 
v.vertr# 
FROM TVERTRAG v 
JOIN TVNEHMER ph ON v.VERTR#=ph.VERTR# 
JOIN TPERSON p ON ph.PERS#=p.PERS# 
--JOIN TNATPERS np ON p.PERS#=np.PERS# 
WHERE v.FIRMA='DE' 
AND v.VERTR# = '8b0e084c-f739-11ee-9ebe-005056b2032c'
AND v.STADIUM='3' 
AND v.ZUSTAND='A' 
--AND v.ZAHLWEISE = 'J'
AND v.VERTRART = 'RA'
--AND v.KONTOSTATUS<>'3' 
),-- BN Contracts select: Policy holder, Natural Person, Active contracts (Motor, Home, Liability, Travel), kontostatus<>3
VTVERTRAG as (select 'TVERTRAG' as table_name, VERTR#, GF#, XMLELEMENT(name "TVERTRAG", XMLFOREST(VERTR#, cast(trim(FIRMA) as blob(4k)) as FIRMA, cast(trim(DION) as blob(4k)) as DION, cast(trim(HSP_EIGEN) as blob(4k)) as HSP_EIGEN, cast(trim(POLLFNR) as blob(4k)) as POLLFNR, cast(trim(VERTRART) as blob(4k)) as VERTRART, cast(trim(STADIUM) as blob(4k)) as STADIUM, BEGDAT, WIRKBEGDAT, ABLDAT, cast(trim(HPTFLLG) as blob(4k)) as HPTFLLG, cast(trim(WERBERNR) as blob(4k)) as WERBERNR, HAFTAENDDAT, cast(trim(KZDECKUNG) as blob(4k)) as KZDECKUNG, cast(trim(KZWILLENSERKL) as blob(4k)) as KZWILLENSERKL, cast(trim(KZTYPBUEND) as blob(4k)) as KZTYPBUEND, cast(trim(FLOTTENNR) as blob(4k)) as FLOTTENNR, cast(trim(TARIFBEREICH) as blob(4k)) as TARIFBEREICH, cast(trim(ZUSTAND) as blob(4k)) as ZUSTAND, cast(trim(HSP_PRODKBEZ) as blob(4k)) as HSP_PRODKBEZ, cast(trim(KONTOSTATUS) as blob(4k)) as KONTOSTATUS, STATUSDATUM, FZSDAT, cast(trim(KZPRGUTHLISTE) as blob(4k)) as KZPRGUTHLISTE, cast(trim(KZUJZ) as blob(4k)) as KZUJZ, cast(trim(ZAHLWEISE) as blob(4k)) as ZAHLWEISE, BEZBISDATUM, cast(trim(INKASSOART) as blob(4k)) as INKASSOART, SALDO, cast(trim(KZ_DIREKTMAIL_AKT) as blob(4k)) as KZ_DIREKTMAIL_AKT, cast(trim(KZ_BEILAGEN) as blob(4k)) as KZ_BEILAGEN, cast(trim(FREMDWAEHRUNG) as blob(4k)) as FREMDWAEHRUNG, DARLKAPITAL, SUPRABL, cast(trim(ORIGDOKADR) as blob(4k)) as ORIGDOKADR, DOKANZ, DOKANZ_KOPIE, cast(trim(KOPIEDOKADR) as blob(4k)) as KOPIEDOKADR, cast(trim(KZFAB) as blob(4k)) as KZFAB, cast(trim(AUSFGRUND1) as blob(4k)) as AUSFGRUND1, cast(trim(AUSFGRUND2) as blob(4k)) as AUSFGRUND2, cast(trim(AUSFGRUND3) as blob(4k)) as AUSFGRUND3, cast(trim(VERTRSTATUS) as blob(4k)) as VERTRSTATUS, cast(trim(KZPRGUTH) as blob(4k)) as KZPRGUTH, VERTRSTATUS_DATUM, GF#, NACH_VERTR#, ERS_VERTR#, HSPP#, INK_ADR#, INK_KK#, INK_BK#, ZUSTELL_ADR#, cast(HSP_PRODBEZ as blob(4k)) as HSP_PRODBEZ, cast(trim(KZSAMMELEINZ) as blob(4k)) as KZSAMMELEINZ, cast(trim(KZTAGGABB) as blob(4k)) as KZTAGGABB, cast(trim(VERTRAUSFGRUND) as blob(4k)) as VERTRAUSFGRUND, cast(trim(DLG) as blob(4k)) as DLG, cast(trim(SPARTE_EIGEN_FUEHR) as blob(4k)) as SPARTE_EIGEN_FUEHR, cast(trim(KZ_MEHRERE_IP) as blob(4k)) as KZ_MEHRERE_IP, INK_GGK#, cast(trim(ERNEUERART) as blob(4k)) as ERNEUERART, cast(trim(FLEARLYINVOICE) as blob(4k)) as FLEARLYINVOICE, cast(trim(SALESOFFSHORTTXT) as blob(4k)) as SALESOFFSHORTTXT, cast(trim(CONTRACTSUBTYPE) as blob(4k)) as CONTRACTSUBTYPE, SO#, cast(trim(HSP_GRP) as blob(4k)) as HSP_GRP)) body from TVERTRAG where VERTR# in (select VERTR# from root)),
VTANTRABW as (select 'TANTRABW' as table_name, ANTRABW#, XMLELEMENT(name "TANTRABW", XMLFOREST(ANTRABW#, cast(trim(KZANTRABW) as blob(4k)) as KZANTRABW, cast(ANTRABW_TEXT as blob(4k)) as ANTRABW_TEXT, VERTR#)) body from TANTRABW where VERTR# in (select VERTR# from VTVERTRAG)),
--VTBN1_LIAPREMPARAM as (select 'TBN1_LIAPREMPARAM' as table_name, BN1_LPPARM#, XMLELEMENT(name "TBN1_LIAPREMPARAM", XMLFOREST(BN1_LPPARM#, GEBURTSDATUM, cast(trim(FAMSTAND) as blob(4k)) as FAMSTAND, cast(trim(BERUFSRISIKOGRUPPE) as blob(4k)) as BERUFSRISIKOGRUPPE, cast(trim(BN1_RISKGRPPART) as blob(4k)) as BN1_RISKGRPPART, VERTR#, KFZ_LAENGE, LEISTUNG, BAUARTGESCHW)) body from TBN1_LIAPREMPARAM where VERTR# in (select VERTR# from VTVERTRAG)),
--VTBN1_MOTPREMPARAM as (select 'TBN1_MOTPREMPARAM' as table_name, BN1_MPPARM#, XMLELEMENT(name "TBN1_MOTPREMPARAM", XMLFOREST(BN1_MPPARM#, cast(trim(POSTLEITZAHL) as blob(4k)) as POSTLEITZAHL, GEBURTSDATUM, EIGGEW, cast(trim(AUFBAU) as blob(4k)) as AUFBAU, LEISTUNG, BN1_MANUFACTORDATE, cast(trim(MARKE) as blob(4k)) as MARKE, cast(trim(MODELL) as blob(4k)) as MODELL, cast(trim(TYP) as blob(4k)) as TYP, cast(trim(KRAFTSTOFFART) as blob(4k)) as KRAFTSTOFFART, BN1_ACCELERATION, cast(trim(BN1_TURBO) as blob(4k)) as BN1_TURBO, cast(trim(BN1_DRIVE) as blob(4k)) as BN1_DRIVE, cast(trim(GETRIEBEART) as blob(4k)) as GETRIEBEART, cast(trim(FARBE) as blob(4k)) as FARBE, NEUPREIS, BN1_EXPECTMILEAGE, SONDERAUSST, SITZPLATZANZ, HUBRAUM, CO2EMISSION, NUTZLAST, HOECHSTGESCHW, cast(trim(BN1_ELECARPP) as blob(4k)) as BN1_ELECARPP, BN1_NBS_DOORS, cast(trim(KZABS) as blob(4k)) as KZABS, cast(trim(ROLLE_BEZ) as blob(4k)) as ROLLE_BEZ, cast(trim(BN1_DEDUCT_VAT) as blob(4k)) as BN1_DEDUCT_VAT, VERTR#, BN1_VALCONST, BN1_VALHHLUG, cast(trim(BN1_KZHAILROOF) as blob(4k)) as BN1_KZHAILROOF, BN1_POWERWEIGHT, BN1_NEWPRICEEXVAT, cast(trim(BN1_DIVCODE) as blob(4k)) as BN1_DIVCODE, cast(trim(BN1_NEWPRICEDESC) as blob(4k)) as BN1_NEWPRICEDESC, cast(trim(BN1_SPORTSCAR) as blob(4k)) as BN1_SPORTSCAR)) body from TBN1_MOTPREMPARAM where VERTR# in (select VERTR# from VTVERTRAG)),
--VTBN1_PROPREMPARAM as (select 'TBN1_PROPREMPARAM' as table_name, BN1_PPPARM#, XMLELEMENT(name "TBN1_PROPREMPARAM", XMLFOREST(BN1_PPPARM#, cast(trim(BAUART) as blob(4k)) as BAUART, cast(trim(DACHUNGSART) as blob(4k)) as DACHUNGSART, cast(trim(GEBKATEGORIE) as blob(4k)) as GEBKATEGORIE, cast(trim(NUTZUNG) as blob(4k)) as NUTZUNG, cast(trim(ROLLE) as blob(4k)) as ROLLE, HERSTELLUNGSJAHR, cast(trim(BN1_THEFTPROT) as blob(4k)) as BN1_THEFTPROT, cast(trim(POSTLEITZAHL) as blob(4k)) as POSTLEITZAHL, cast(trim(SACHZUSKBEZ) as blob(4k)) as SACHZUSKBEZ, cast(trim(BN1_FLATDET) as blob(4k)) as BN1_FLATDET, GEBURTSDATUM, cast(trim(FAMSTAND) as blob(4k)) as FAMSTAND, SWERT, BAUWERT, SUMMEWERTERM, VERTR#, cast(trim(BN1_KZUNDERCONSTR) as blob(4k)) as BN1_KZUNDERCONSTR, cast(trim(KZBEWOHNT) as blob(4k)) as KZBEWOHNT, BN1_RENTPRICE, cast(trim(KZKELLER) as blob(4k)) as KZKELLER, cast(trim(BN1_HEATINGSYS) as blob(4k)) as BN1_HEATINGSYS, cast(trim(BN1_KZDECOFIREPLAC) as blob(4k)) as BN1_KZDECOFIREPLAC, BN1_HABIROOMTOT, BN1_NONHABIROOMTOT, cast(trim(BN1_KZOAKMARBLE) as blob(4k)) as BN1_KZOAKMARBLE)) body from TBN1_PROPREMPARAM where VERTR# in (select VERTR# from VTVERTRAG)),
--VTBN1_VERTRAG as (select 'TBN1_VERTRAG' as table_name, BN1_VERTR#, XMLELEMENT(name "TBN1_VERTRAG", XMLFOREST(BN1_VERTR#, cast(trim(BN1_COLLMODE) as blob(4k)) as BN1_COLLMODE, VERTR#, cast(BN1_REMITTANCEID as blob(4k)) as BN1_REMITTANCEID, cast(trim(BN1_CNTRLTYP) as blob(4k)) as BN1_CNTRLTYP, cast(trim(BN1_CNTRLRES) as blob(4k)) as BN1_CNTRLRES, BN1_COUNT1STDUNN, BN1_CUMMINVDAYS, BN1_COUNTINVPAID, BN1_AVGINVDAYS, cast(trim(BN1_KZBANKOPTIN) as blob(4k)) as BN1_KZBANKOPTIN, cast(trim(BN1_GROUPINGCODE) as blob(4k)) as BN1_GROUPINGCODE)) body from TBN1_VERTRAG where VERTR# in (select VERTR# from VTVERTRAG)),
VTGSCHFALL as (select 'TGSCHFALL' as table_name, GF#, XMLELEMENT(name "TGSCHFALL", XMLFOREST(GF#, BEGINN, AENDERUNG, cast(trim(FIRMA) as blob(4k)) as FIRMA, cast(trim(GESCHFALL) as blob(4k)) as GESCHFALL, cast(trim(QUELLE) as blob(4k)) as QUELLE, GSTUEBERNZEIT, cast(trim(KZLOESCHUNG) as blob(4k)) as KZLOESCHUNG, cast(trim(GPSTATUS) as blob(4k)) as GPSTATUS, cast(trim(ERSTELLUSER) as blob(4k)) as ERSTELLUSER, cast(trim(SPERRUSER) as blob(4k)) as SPERRUSER, cast(trim(SPRACHE) as blob(4k)) as SPRACHE, AENDZP, cast(trim(ZEITZONE) as blob(4k)) as ZEITZONE, cast(trim(FLLOCK) as blob(4k)) as FLLOCK)) body from TGSCHFALL where GF# in (select GF# from VTVERTRAG)),
VTKLAGE as (select 'TKLAGE' as table_name, KG#, XMLELEMENT(name "TKLAGE", XMLFOREST(KG#, WEITERGABEDAT, cast(trim(EINST_VERANL) as blob(4k)) as EINST_VERANL, cast(trim(KLAGSEINSTKZ) as blob(4k)) as KLAGSEINSTKZ, KLAGSEINSTDAT, cast(trim(ERLKZ) as blob(4k)) as ERLKZ, ERLDAT, cast(trim(KOSTENTRAEGER) as blob(4k)) as KOSTENTRAEGER, KLAGSBETRAG, BARAUSLAGEN, ANWKOSTEN_EIGEN, ANWKOSTEN_FREMD, TAGSATZTERMIN, cast(trim(GERICHTSZAHL) as blob(4k)) as GERICHTSZAHL, cast(trim(KLAGESTATUS) as blob(4k)) as KLAGESTATUS, KLAGESTATUS_DATUM, ADR#, VERTR#, cast(KLAGSBEM as blob(4k)) as KLAGSBEM, cast(trim(KLAGENUMMER) as blob(4k)) as KLAGENUMMER)) body from TKLAGE where VERTR# in (select VERTR# from VTVERTRAG)),
VTKTOSTG as (select 'TKTOSTG' as table_name, KTOSTG#, XMLELEMENT(name "TKTOSTG", XMLFOREST(KTOSTG#, DOKANZ, cast(trim(INKADRESSAT) as blob(4k)) as INKADRESSAT, LETZTRATDAT, cast(trim(RUECKLAUFGR) as blob(4k)) as RUECKLAUFGR, MAHNSTOP_ENDE, MAHNSTOP_BEGINN, RUECKLDAT, cast(trim(AKTIVITAET1) as blob(4k)) as AKTIVITAET1, cast(trim(AKTIVITAET2) as blob(4k)) as AKTIVITAET2, cast(trim(AKTIVITAET3) as blob(4k)) as AKTIVITAET3, WERTBERICHTG, ABBUCHSPERRE_BIS, VERTR#, cast(VKTOBEM as blob(4k)) as VKTOBEM, LSVERZ_ANZTAGE, cast(trim(MAHNDATAENDGR) as blob(4k)) as MAHNDATAENDGR, cast(trim(RVBVTART) as blob(4k)) as RVBVTART)) body from TKTOSTG where VERTR# in (select VERTR# from VTVERTRAG)),
VTPOLTXT_VERTR as (select 'TPOLTXT_VERTR' as table_name, PTV#, XMLELEMENT(name "TPOLTXT_VERTR", XMLFOREST(PTV#, SORTIERUNG, cast(trim(TEXTART) as blob(4k)) as TEXTART, VERTR#, cast(VERTRTEXT as blob(4k)) as VERTRTEXT)) body from TPOLTXT_VERTR where VERTR# in (select VERTR# from VTVERTRAG)),
VTVEINDVER as (select 'TVEINDVER' as table_name, VIV#, XMLELEMENT(name "TVEINDVER", XMLFOREST(VIV#, SORTIERUNG, VERTR#, cast(VEREINBARUNG as blob(4k)) as VEREINBARUNG, cast(trim(KZINDVBG_PRUEF) as blob(4k)) as KZINDVBG_PRUEF, cast(trim(FLCLAIMRELEVANT) as blob(4k)) as FLCLAIMRELEVANT)) body from TVEINDVER where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERAENDSCHICHT as (select 'TVERAENDSCHICHT' as table_name, VS#, XMLELEMENT(name "TVERAENDSCHICHT", XMLFOREST(VS#, WIRKBEGDAT, VSCHICHT_REIHUNG, cast(trim(AUSFGRUND1) as blob(4k)) as AUSFGRUND1, cast(trim(GFAKTIVITAET) as blob(4k)) as GFAKTIVITAET, cast(trim(KZVERARB_VSCHICHT) as blob(4k)) as KZVERARB_VSCHICHT, VERTR#, cast(trim(VERTRAUSFGRUND) as blob(4k)) as VERTRAUSFGRUND)) body from TVERAENDSCHICHT where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERSVERTRAG as (select 'TVERSVERTRAG' as table_name, VERSV#, XMLELEMENT(name "TVERSVERTRAG", XMLFOREST(VERSV#, SORTIERUNG, cast(trim(SPARTE_EIGEN) as blob(4k)) as SPARTE_EIGEN, cast(trim(ZUSTAND) as blob(4k)) as ZUSTAND, BEGINNDAT, ABLAUFDAT, WIRKBEGINN, TARIFDATUM, LERNEUDAT, cast(trim(BEDINGUNG) as blob(4k)) as BEDINGUNG, cast(trim(TARIF) as blob(4k)) as TARIF, SPROZ, JPRNETTO, JPRBRUTTO, EIGENANTEIL, DAUERRABATT, BUENDELRABATT, VERGVRABATT, SANZUSCHL, cast(trim(RISIKOKLASSE) as blob(4k)) as RISIKOKLASSE, cast(trim(KZINDEX) as blob(4k)) as KZINDEX, cast(trim(VERTZUSTDET) as blob(4k)) as VERTZUSTDET, BEOBENDE, cast(trim(KZBEARBEITBAR) as blob(4k)) as KZBEARBEITBAR, SPP#, cast(trim(SP_PRODKBEZ) as blob(4k)) as SP_PRODKBEZ, cast(trim(SP_GRP) as blob(4k)) as SP_GRP, BEGINNVERLDAT, cast(trim(BDL_CODE) as blob(4k)) as BDL_CODE, cast(trim(KZLOHNSUMMABR) as blob(4k)) as KZLOHNSUMMABR, cast(trim(KZVST) as blob(4k)) as KZVST, VERTR#, cast(VARIANTE as blob(4k)) as VARIANTE, cast(SP_PRODBEZ as blob(4k)) as SP_PRODBEZ, INLANDSANTEIL, JPRNETTO100, cast(trim(ZUSKOSPEZREGEL) as blob(4k)) as ZUSKOSPEZREGEL, cast(trim(SANKZ) as blob(4k)) as SANKZ, cast(trim(DECKUNGSGRUPPE) as blob(4k)) as DECKUNGSGRUPPE, VVLAUFNR, cast(trim(MELDEPFLICHT) as blob(4k)) as MELDEPFLICHT, cast(trim(ADDITIONALCOVER) as blob(4k)) as ADDITIONALCOVER)) body from TVERSVERTRAG where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERTR_SONSTROLL as (select 'TVERTR_SONSTROLL' as table_name, VERTRSR#, XMLELEMENT(name "TVERTR_SONSTROLL", XMLFOREST(VERTRSR#, VERTR#, PERS#, cast(trim(VERTRSONSTROLLBEZ) as blob(4k)) as VERTRSONSTROLLBEZ)) body from TVERTR_SONSTROLL where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERTRAG_GEN as (select 'TVERTRAG_GEN' as table_name, VGEN#, XMLELEMENT(name "TVERTRAG_GEN", XMLFOREST(VGEN#, FACHGEBGRPNR, cast(trim(ABEZ) as blob(4k)) as ABEZ, VERTR#, cast(AINHALT as blob(4k)) as AINHALT)) body from TVERTRAG_GEN where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERTRAUFWKTO as (select 'TVERTRAUFWKTO' as table_name, VAWKTO#, XMLELEMENT(name "TVERTRAUFWKTO", XMLFOREST(VAWKTO#, SUMME_AUFWAND, VERTR#)) body from TVERTRAUFWKTO where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERTRBEZUG as (select 'TVERTRBEZUG' as table_name, VERTRBEZ#, XMLELEMENT(name "TVERTRBEZUG", XMLFOREST(VERTRBEZ#, cast(trim(FIRMA) as blob(4k)) as FIRMA, cast(trim(POLLFNR) as blob(4k)) as POLLFNR, cast(trim(VERTRBEZUGSBEZ) as blob(4k)) as VERTRBEZUGSBEZ, VERTR#, cast(trim(POLNR_VORSYS) as blob(4k)) as POLNR_VORSYS, cast(trim(POLNR_VORSYSINT) as blob(4k)) as POLNR_VORSYSINT, cast(trim(VORSYS) as blob(4k)) as VORSYS, cast(trim(VERGEB_FA) as blob(4k)) as VERGEB_FA, cast(trim(HSP_EIGEN) as blob(4k)) as HSP_EIGEN, cast(trim(SPARTE_EIGEN) as blob(4k)) as SPARTE_EIGEN, cast(trim(SPARTE_EIGEN_BEZ) as blob(4k)) as SPARTE_EIGEN_BEZ)) body from TVERTRBEZUG where VERTR# in (select VERTR# from VTVERTRAG)),
VTVERTRZUS as (select 'TVERTRZUS' as table_name, VZUS#, XMLELEMENT(name "TVERTRZUS", XMLFOREST(VZUS#, LBESWDAT, KUENDSTITAG, ERKLABGABDAT, cast(trim(DEPOTNR) as blob(4k)) as DEPOTNR, cast(trim(POLNR_VORSYS) as blob(4k)) as POLNR_VORSYS, cast(trim(POLNR_VORSYSINT) as blob(4k)) as POLNR_VORSYSINT, cast(trim(VORSYS) as blob(4k)) as VORSYS, cast(trim(VERGEB_FA) as blob(4k)) as VERGEB_FA, cast(trim(VERG_KNAME) as blob(4k)) as VERG_KNAME, CCC_EINGZP, cast(trim(CCC_EINGMED) as blob(4k)) as CCC_EINGMED, cast(trim(ZG_USERID) as blob(4k)) as ZG_USERID, AS_ZGZP, AS_ERLZP, cast(trim(LOKTECHNAME) as blob(4k)) as LOKTECHNAME, TEAMEINGDAT, cast(trim(GA_BETREUER) as blob(4k)) as GA_BETREUER, ANTRAGSPOLDAT, PRAEMDEP#, WIRTBER_ADR#, KREDIT_BK#, VERTR#, VRG#, DGK#, cast(AS_RGGRUND as blob(4k)) as AS_RGGRUND, cast(trim(FACHGRUPPE) as blob(4k)) as FACHGRUPPE, cast(trim(ZG_TEAM) as blob(4k)) as ZG_TEAM, cast(trim(BEARBUSERID) as blob(4k)) as BEARBUSERID, cast(trim(KZVERTEILBAR) as blob(4k)) as KZVERTEILBAR, STO_DATUM, cast(trim(VERTZUSTDET) as blob(4k)) as VERTZUSTDET, cast(trim(VERGBEZROLLE) as blob(4k)) as VERGBEZROLLE, cast(trim(VERTRDOKADR) as blob(4k)) as VERTRDOKADR, cast(trim(FOLGEDOKADR) as blob(4k)) as FOLGEDOKADR, cast(trim(SCHADDOKADR) as blob(4k)) as SCHADDOKADR, cast(trim(KZVERZOFFPRAEM) as blob(4k)) as KZVERZOFFPRAEM, cast(trim(KZRUECKREP) as blob(4k)) as KZRUECKREP, SUMBEZPR, cast(FREMDVERMITTLER as blob(4k)) as FREMDVERMITTLER, cast(trim(KZBRUTTO) as blob(4k)) as KZBRUTTO, cast(trim(KZVORABWTG) as blob(4k)) as KZVORABWTG, cast(trim(LOKTECHNAME_PERM) as blob(4k)) as LOKTECHNAME_PERM, cast(trim(KZBESROUTGR) as blob(4k)) as KZBESROUTGR, cast(trim(KZROUTKRITSCHAD) as blob(4k)) as KZROUTKRITSCHAD, VERG_GENERATION, cast(RAHMENVERTRNAME as blob(4k)) as RAHMENVERTRNAME, cast(trim(ANTRABLGRUND) as blob(4k)) as ANTRABLGRUND, cast(trim(VORSCHLAGSNR) as blob(4k)) as VORSCHLAGSNR, cast(trim(EINVOICECHANNEL) as blob(4k)) as EINVOICECHANNEL, EINV_KO#, cast(trim(FREMDPOLNR) as blob(4k)) as FREMDPOLNR, INK_PC#)) body from TVERTRZUS where VERTR# in (select VERTR# from VTVERTRAG)),
VTVNEHMER as (select 'TVNEHMER' as table_name, VERTR#, PERS#, XMLELEMENT(name "TVNEHMER", XMLFOREST(VERTR#, PERS#, cast(trim(KZHAUPTVN) as blob(4k)) as KZHAUPTVN, cast(trim(VNEHMERDETBEZ) as blob(4k)) as VNEHMERDETBEZ)) body from TVNEHMER where VERTR# in (select VERTR# from VTVERTRAG)),
--VTBN1_BMDETAILS as (select 'TBN1_BMDETAILS' as table_name, BN1_BMDETAILS#, XMLELEMENT(name "TBN1_BMDETAILS", XMLFOREST(BN1_BMDETAILS#, cast(trim(BN1_BMLEVEL) as blob(4k)) as BN1_BMLEVEL, BN1_CFYEXT, cast(trim(BN1_BMREASON) as blob(4k)) as BN1_BMREASON, BN1_CFY, VERSV#, BN1_BMCOMMSTEP, BN1_PHAGESTEP, ANZVORSCH, BN1_YRSOFPROOF, BN1_OBSERVSTRDTBM, BN1_OBSERVSTRDTSC, BN1_COUNTERSC)) body from TBN1_BMDETAILS where VERSV# in (select VERSV# from VTVERSVERTRAG)),
--VTBN1_VERSVERTRAG as (select 'TBN1_VERSVERTRAG' as table_name, BN1_VERSV#, XMLELEMENT(name "TBN1_VERSVERTRAG", XMLFOREST(BN1_VERSV#, cast(trim(BN1_SOZVB) as blob(4k)) as BN1_SOZVB, VERSV#)) body from TBN1_VERSVERTRAG where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTBOMAAUSK as (select 'TBOMAAUSK' as table_name, BOMA#, XMLELEMENT(name "TBOMAAUSK", XMLFOREST(BOMA#, cast(trim(ANSTALTSNR) as blob(4k)) as ANSTALTSNR, cast(trim(FREMDPOLNR) as blob(4k)) as FREMDPOLNR, FVBEGINN, FVENDE, VRBEOBENDE, cast(trim(KZENDE) as blob(4k)) as KZENDE, cast(trim(KFZKZLAND) as blob(4k)) as KFZKZLAND, cast(trim(KFZKZ) as blob(4k)) as KFZKZ, cast(trim(VRSTUFE) as blob(4k)) as VRSTUFE, cast(trim(EIGERWANG) as blob(4k)) as EIGERWANG, cast(trim(EVFIRMA) as blob(4k)) as EVFIRMA, cast(trim(EVPOLLFNR) as blob(4k)) as EVPOLLFNR, ANZVORSCH, EREIGDAT1, EREIGDAT2, EREIGDAT3, EREIGDAT4, EREIGDAT5, EREIGDAT6, VERSV#)) body from TBOMAAUSK where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTINDIZIERUNG as (select 'TINDIZIERUNG' as table_name, IDZ#, XMLELEMENT(name "TINDIZIERUNG", XMLFOREST(IDZ#, IXWERT, IXANWMON, AUSGIXWERT, AUSGIXMON, cast(trim(BDL_CODE) as blob(4k)) as BDL_CODE, cast(trim(BEZUGSWERT) as blob(4k)) as BEZUGSWERT, VERSV#, cast(trim(INDEXART) as blob(4k)) as INDEXART)) body from TINDIZIERUNG where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTINDVER as (select 'TINDVER' as table_name, IV#, XMLELEMENT(name "TINDVER", XMLFOREST(IV#, SORTIERUNG, VERSV#, cast(VEREINBARUNG as blob(4k)) as VEREINBARUNG, cast(trim(KZINDVBG_PRUEF) as blob(4k)) as KZINDVBG_PRUEF, cast(trim(FLCLAIMRELEVANT) as blob(4k)) as FLCLAIMRELEVANT)) body from TINDVER where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTINDVORRUECKRECH as (select 'TINDVORRUECKRECH' as table_name, INDVR#, XMLELEMENT(name "TINDVORRUECKRECH", XMLFOREST(INDVR#, VORRABDAT, RUECKABDAT, cast(trim(KZBRUTTO) as blob(4k)) as KZBRUTTO, cast(trim(KZUJZ) as blob(4k)) as KZUJZ, cast(trim(KZVST) as blob(4k)) as KZVST, VORBETRAG, RUECKBETRAG, VERSV#)) body from TINDVORRUECKRECH where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTPRODAUS as (select 'TPRODAUS' as table_name, PAP#, XMLELEMENT(name "TPRODAUS", XMLFOREST(PAP#, SORTIERUNG5, SUMME, cast(trim(SUMARTBEZ) as blob(4k)) as SUMARTBEZ, JAHRESTPR_NETTO, cast(trim(BAUSTEINTYP) as blob(4k)) as BAUSTEINTYP, ANZEBENE, cast(trim(KZSACHART) as blob(4k)) as KZSACHART, cast(trim(KZWANPAUS) as blob(4k)) as KZWANPAUS, FAKTOR, PBLAUFNR, INSTANZID, cast(trim(ENTSCHAEDWERT) as blob(4k)) as ENTSCHAEDWERT, VERSV#, PSCHABL#, cast(PRODBAUBEZ as blob(4k)) as PRODBAUBEZ, JAHRESTPR_NETTO100, UEBERINSTANZID, TECHN_PREIS, cast(trim(FLWEBHIDDEN) as blob(4k)) as FLWEBHIDDEN, JAHRESTPR_NETTO_ZA, cast(trim(ADDITIONALCOVER) as blob(4k)) as ADDITIONALCOVER)) body from TPRODAUS where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTPROVANSPRUCH as (select 'TPROVANSPRUCH' as table_name, PANSP#, XMLELEMENT(name "TPROVANSPRUCH", XMLFOREST(PANSP#, cast(trim(PROVART) as blob(4k)) as PROVART, ANSPRVON, ANSPRBIS, cast(trim(KZPENSANSPR) as blob(4k)) as KZPENSANSPR, GEKUERZT, GEKUERZTAM, PROVANTEIL, WAHRLIMIT, cast(trim(KZQUELLE) as blob(4k)) as KZQUELLE, cast(trim(KZEINMALIG) as blob(4k)) as KZEINMALIG, PROVWERT, cast(trim(WERTEINH) as blob(4k)) as WERTEINH, cast(trim(BEZUGSBASIS) as blob(4k)) as BEZUGSBASIS, MAXWERT, cast(trim(MAXEINHEIT) as blob(4k)) as MAXEINHEIT, RRZR, AUSZZR, cast(trim(PROVSCHEMABEZUG) as blob(4k)) as PROVSCHEMABEZUG, cast(trim(PROVROLLE) as blob(4k)) as PROVROLLE, PBLAUFNR, VERSV#, PKTO#, cast(FREMDVERMITTLER as blob(4k)) as FREMDVERMITTLER, cast(trim(ISTVERRECHNUNG) as blob(4k)) as ISTVERRECHNUNG)) body from TPROVANSPRUCH where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTSCHADEN as (select 'TSCHADEN' as table_name, SCH#, EREI#, XMLELEMENT(name "TSCHADEN", XMLFOREST(SCH#, cast(trim(FIRMA) as blob(4k)) as FIRMA, cast(trim(POLLFNR) as blob(4k)) as POLLFNR, ANLAGEJAHR, cast(trim(NUMMER) as blob(4k)) as NUMMER, cast(trim(KATEGORIE) as blob(4k)) as KATEGORIE, SCHADEN_ZP, cast(trim(HSP_EIGEN) as blob(4k)) as HSP_EIGEN, cast(trim(SPARTE_EIGEN) as blob(4k)) as SPARTE_EIGEN, cast(trim(KZREGRESS) as blob(4k)) as KZREGRESS, cast(trim(KZFINGIERT) as blob(4k)) as KZFINGIERT, cast(trim(PRAEMDECKPRUE) as blob(4k)) as PRAEMDECKPRUE, cast(trim(VERTRDECKPRUE) as blob(4k)) as VERTRDECKPRUE, cast(trim(RISIKDECKPRUE) as blob(4k)) as RISIKDECKPRUE, SPEICHERDAUER, cast(trim(KZFESTSTELLUNGSAKT) as blob(4k)) as KZFESTSTELLUNGSAKT, cast(trim(KZBONUSERHALTEND) as blob(4k)) as KZBONUSERHALTEND, cast(trim(KZVNMELDUNG) as blob(4k)) as KZVNMELDUNG, SCHLDAT, cast(trim(BEARBUSERID) as blob(4k)) as BEARBUSERID, VERSCHULDPROZ, cast(trim(SARTKBEZ) as blob(4k)) as SARTKBEZ, cast(trim(SURSKBEZ) as blob(4k)) as SURSKBEZ, SU_RUECKSTBEDARF, SU_REGRESS_EINB, SU_REGRESS_EINZ, SU_ENTSCH, SU_TEILAB, SU_KULANZ, SU_SPESEN, cast(trim(LOKTECHNAME) as blob(4k)) as LOKTECHNAME, SCHLDAT_ALT, TEAMEINGDAT, cast(trim(KZ_FWBUCHUNG) as blob(4k)) as KZ_FWBUCHUNG, cast(trim(KZSCHADSCHL) as blob(4k)) as KZSCHADSCHL, cast(trim(KZSCHADPRIORITAET) as blob(4k)) as KZSCHADPRIORITAET, cast(trim(SCHADSTATUS) as blob(4k)) as SCHADSTATUS, SCHADSTATUS_DATUM, cast(trim(DECKPRUEERG) as blob(4k)) as DECKPRUEERG, cast(trim(DECKGRUND) as blob(4k)) as DECKGRUND, cast(trim(VERSCHPRUE) as blob(4k)) as VERSCHPRUE, cast(trim(OBLIEGVERL) as blob(4k)) as OBLIEGVERL, cast(trim(BETRUGBEURT) as blob(4k)) as BETRUGBEURT, cast(trim(KZPAPIERAKT) as blob(4k)) as KZPAPIERAKT, cast(trim(GESAMTDECK) as blob(4k)) as GESAMTDECK, CCC_EINGZP, cast(trim(CCC_EINGMED) as blob(4k)) as CCC_EINGMED, GF#, VERSV#, EREI#, EINABR#, cast(trim(FACHGRUPPE) as blob(4k)) as FACHGRUPPE, cast(trim(FREMDWAEHRUNG) as blob(4k)) as FREMDWAEHRUNG, cast(trim(INTCOMPAGREEMENT) as blob(4k)) as INTCOMPAGREEMENT, cast(trim(FLLEADINGCLAIM) as blob(4k)) as FLLEADINGCLAIM)) body from TSCHADEN where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTSCHICHTPROT as (select 'TSCHICHTPROT' as table_name, SPRO#, XMLELEMENT(name "TSCHICHTPROT", XMLFOREST(SPRO#, cast(trim(TABLE_NAME) as blob(4k)) as TABLE_NAME, TABLE_PK1, TABLE_PK2, cast(trim(VERARBEITUNGS_KZ) as blob(4k)) as VERARBEITUNGS_KZ, VS#, cast(SSCHLTEIL as blob(4k)) as SSCHLTEIL)) body from TSCHICHTPROT where VS# in (select VS# from VTVERAENDSCHICHT)),
VTVERAENDSCHICHT_LZ as (select 'TVERAENDSCHICHT_LZ' as table_name, VS#, LAUFZ#, XMLELEMENT(name "TVERAENDSCHICHT_LZ", XMLFOREST(VS#, LAUFZ#)) body from TVERAENDSCHICHT_LZ where VS# in (select VS# from VTVERAENDSCHICHT)),
VTVERSVERTRAG_GEN as (select 'TVERSVERTRAG_GEN' as table_name, VVGEN#, XMLELEMENT(name "TVERSVERTRAG_GEN", XMLFOREST(VVGEN#, FACHGEBGRPNR, cast(trim(ABEZ) as blob(4k)) as ABEZ, VERSV#, cast(AINHALT as blob(4k)) as AINHALT)) body from TVERSVERTRAG_GEN where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTVINKGL as (select 'TVINKGL' as table_name, VINKGL#, XMLELEMENT(name "TVINKGL", XMLFOREST(VINKGL#, VERSV#, PERS#, cast(trim(RANGFOLGE) as blob(4k)) as RANGFOLGE, VINK_BETR, UNANF_BETR, cast(trim(VINKGLART) as blob(4k)) as VINKGLART, cast(trim(KZUNANFECHTBAR) as blob(4k)) as KZUNANFECHTBAR, cast(trim(POLIZZENNR) as blob(4k)) as POLIZZENNR, cast(trim(ANSTALTSNR) as blob(4k)) as ANSTALTSNR, cast(VINKOBJ as blob(4k)) as VINKOBJ, cast(ZUHANDEN as blob(4k)) as ZUHANDEN, cast(AKTENNR as blob(4k)) as AKTENNR, cast(BRIEFTEXT as blob(4k)) as BRIEFTEXT, EINGDAT, cast(trim(VINKROLLEBEZ) as blob(4k)) as VINKROLLEBEZ, GILTAB, GILTBIS, cast(trim(VINKGLARTDET) as blob(4k)) as VINKGLARTDET, cast(trim(FLLEGALSCOPE) as blob(4k)) as FLLEGALSCOPE, cast(trim(FLSCOPEFEATURES) as blob(4k)) as FLSCOPEFEATURES, cast(trim(FLENTBENREVSCOPE) as blob(4k)) as FLENTBENREVSCOPE, cast(trim(POSTLANDSCHL) as blob(4k)) as POSTLANDSCHL, cast(trim(FLAGAINSTROLE) as blob(4k)) as FLAGAINSTROLE, cast(trim(FLBENOBL) as blob(4k)) as FLBENOBL, SACH#)) body from TVINKGL where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTVVZUABSCHLAG as (select 'TVVZUABSCHLAG' as table_name, VVZA#, XMLELEMENT(name "TVVZUABSCHLAG", XMLFOREST(VVZA#, cast(trim(VVZUABART) as blob(4k)) as VVZUABART, BERREIHENFOLGE, VVZUABPROZ, GILTBIS, VERSV#, cast(trim(KZ_ENTH_JTPR_NETTO) as blob(4k)) as KZ_ENTH_JTPR_NETTO, cast(VVZUABSCHLAGGRUND as blob(4k)) as VVZUABSCHLAGGRUND)) body from TVVZUABSCHLAG where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTZUSKOSTEN as (select 'TZUSKOSTEN' as table_name, ZK#, XMLELEMENT(name "TZUSKOSTEN", XMLFOREST(ZK#, cast(trim(ZUSKART) as blob(4k)) as ZUSKART, ZUSKBETR, PROZENT, cast(trim(BEFRGRUND) as blob(4k)) as BEFRGRUND, VERSV#, cast(trim(POSTLANDSCHL) as blob(4k)) as POSTLANDSCHL, SORTIERUNG, cast(trim(KZVONNETTOPR) as blob(4k)) as KZVONNETTOPR, BEMGRPROZ, cast(trim(BDL_CODE) as blob(4k)) as BDL_CODE)) body from TZUSKOSTEN where VERSV# in (select VERSV# from VTVERSVERTRAG)),
VTBEZUGSRECHT as (select 'TBEZUGSRECHT' as table_name, BEZRE#, XMLELEMENT(name "TBEZUGSRECHT", XMLFOREST(BEZRE#, cast(trim(BEZRECHT_RISIKO) as blob(4k)) as BEZRECHT_RISIKO, cast(trim(BEZRECHTART) as blob(4k)) as BEZRECHTART, PAP#, cast(trim(KZUNWIDERRUFLICH) as blob(4k)) as KZUNWIDERRUFLICH, EINGDAT, BEZRECHT_RANGF)) body from TBEZUGSRECHT where PAP# in (select PAP# from VTPRODAUS)),
VTEREIGNIS as (select 'TEREIGNIS' as table_name, EREI#, XMLELEMENT(name "TEREIGNIS", XMLFOREST(EREI#, ENDZP, BEGINNZP, cast(trim(KZBEGINNFING) as blob(4k)) as KZBEGINNFING, cast(trim(ERARTKBEZ) as blob(4k)) as ERARTKBEZ, cast(trim(ERURSKBEZ) as blob(4k)) as ERURSKBEZ, cast(trim(KZBEHOERDAUFN) as blob(4k)) as KZBEHOERDAUFN, GF#, cast(trim(KZEREIGNISTYP) as blob(4k)) as KZEREIGNISTYP, cast(EREIGNISBEZ as blob(4k)) as EREIGNISBEZ, cast(trim(LOSSEVENTCODE) as blob(4k)) as LOSSEVENTCODE)) body from TEREIGNIS where EREI# in (select EREI# from VTSCHADEN)),
VTSCHICHTPROT_TUP as (select 'TSCHICHTPROT_TUP' as table_name, SPRO_TUP#, XMLELEMENT(name "TSCHICHTPROT_TUP", XMLFOREST(SPRO_TUP#, SPRO#, cast(TUPEL_PIC as blob(4k)) as TUPEL_PIC)) body from TSCHICHTPROT_TUP where SPRO# in (select SPRO# from VTSCHICHTPROT)),
VTTARIFGRUNDL as (select 'TTARIFGRUNDL' as table_name, TARGRDL#, XMLELEMENT(name "TTARIFGRUNDL", XMLFOREST(TARGRDL#, cast(trim(TARIFIERUNGSSCHL) as blob(4k)) as TARIFIERUNGSSCHL, cast(trim(TARIFIERUNGSWERT) as blob(4k)) as TARIFIERUNGSWERT, PAP#)) body from TTARIFGRUNDL where PAP# in (select PAP# from VTPRODAUS)),
VTTXTBWERTINH as (select 'TTXTBWERTINH' as table_name, TXTBWINH#, XMLELEMENT(name "TTXTBWERTINH", XMLFOREST(TXTBWINH#, cast(trim(TBSTREF) as blob(4k)) as TBSTREF, cast(trim(TXTWKBEZ) as blob(4k)) as TXTWKBEZ, PAP#, TXTBETRAG, cast(TXTBWERT as blob(4k)) as TXTBWERT)) body from TTXTBWERTINH where PAP# in (select PAP# from VTPRODAUS)),
VTVERSPERS as (select 'TVERSPERS' as table_name, PAP#, NP#, XMLELEMENT(name "TVERSPERS", XMLFOREST(PAP#, NP#, cast(trim(RISIKOGRUPPE) as blob(4k)) as RISIKOGRUPPE, EINTRALTER, cast(trim(KZHAUPTVP) as blob(4k)) as KZHAUPTVP, cast(trim(KZUNTERSUCHUNG) as blob(4k)) as KZUNTERSUCHUNG, LEISTUNGSSTAFFEL, RUECKSTELLDAUER, cast(trim(KZABLEHNUNG) as blob(4k)) as KZABLEHNUNG, cast(trim(KZERHSPERR) as blob(4k)) as KZERHSPERR, cast(trim(KZRISPRRCKGEWAEHR) as blob(4k)) as KZRISPRRCKGEWAEHR, cast(trim(KZWERKTAETIG) as blob(4k)) as KZWERKTAETIG, RUEFAKTOR, BEITRALTER, LSTAFFELBETR, LSTAFFELBEGINN, LSTAFFELENDE, cast(trim(LEBENSTATUS) as blob(4k)) as LEBENSTATUS, cast(trim(SVANSTALT) as blob(4k)) as SVANSTALT, cast(trim(FAMROLLE) as blob(4k)) as FAMROLLE, cast(trim(ZUSCHLKLASSE) as blob(4k)) as ZUSCHLKLASSE, VP_GEBDAT, cast(trim(VP_ARBVERH) as blob(4k)) as VP_ARBVERH, VP_STERBEDATUM, cast(trim(BERUFSRISIKOGRUPPE) as blob(4k)) as BERUFSRISIKOGRUPPE, cast(trim(RAUCHERSTATUS) as blob(4k)) as RAUCHERSTATUS, KOERPERGROESSE, KOERPERGEWICHT, cast(trim(FAMANAMNESE) as blob(4k)) as FAMANAMNESE, cast(trim(RISIKO_ID) as blob(4k)) as RISIKO_ID, cast(trim(KONFESSION) as blob(4k)) as KONFESSION, PHYSWORKSHARE)) body from TVERSPERS where PAP# in (select PAP# from VTPRODAUS)),
VTVERSSACHE as (select 'TVERSSACHE' as table_name, SACH#, PAP#, XMLELEMENT(name "TVERSSACHE", XMLFOREST(SACH#, PAP#, cast(trim(VERSSACHE_ART) as blob(4k)) as VERSSACHE_ART, cast(trim(KZRVHPTLOK) as blob(4k)) as KZRVHPTLOK, cast(trim(KZNUROB) as blob(4k)) as KZNUROB, cast(trim(RISIKO_ID) as blob(4k)) as RISIKO_ID, cast(trim(NEBENRISIKO_ID) as blob(4k)) as NEBENRISIKO_ID, cast(RISIKO_BESCHR as blob(4k)) as RISIKO_BESCHR, cast(NEBENRISIKO_BESCHR as blob(4k)) as NEBENRISIKO_BESCHR, cast(trim(ZUSKOSPEZREGEL) as blob(4k)) as ZUSKOSPEZREGEL, cast(trim(ZUSKOSPZREGEL_BDL) as blob(4k)) as ZUSKOSPZREGEL_BDL)) body from TVERSSACHE where PAP# in (select PAP# from VTPRODAUS)),
VTSACHE as (select 'TSACHE' as table_name, SACH#, XMLELEMENT(name "TSACHE", XMLFOREST(SACH#, cast(trim(TYP) as blob(4k)) as TYP, MWST, KAUFDAT, HERSTELLUNGSJAHR, cast(trim(ROLLE_BEZ) as blob(4k)) as ROLLE_BEZ, cast(trim(SACHKZ) as blob(4k)) as SACHKZ, cast(trim(KZLEASING) as blob(4k)) as KZLEASING, cast(trim(KZORTVORH) as blob(4k)) as KZORTVORH, ANZVORSCHAEDEN, cast(trim(NUTZUNG) as blob(4k)) as NUTZUNG, GF#, UEBER_SACH#, cast(SACHBEZ as blob(4k)) as SACHBEZ)) body from TSACHE where SACH# in (select SACH# from VTVERSSACHE)),
VTBESITZVERH as (select 'TBESITZVERH' as table_name, PERS#, ROLLE, SACH#, XMLELEMENT(name "TBESITZVERH", XMLFOREST(PERS#, SACH#, cast(trim(ROLLE) as blob(4k)) as ROLLE)) body from TBESITZVERH where SACH# in (select SACH# from VTSACHE)),
VTKFZ as (select 'TKFZ' as table_name, KFZ#, XMLELEMENT(name "TKFZ", XMLFOREST(KFZ#, cast(trim(MARKE) as blob(4k)) as MARKE, cast(trim(MODELL) as blob(4k)) as MODELL, cast(TYPE as blob(4k)) as TYPE, SITZPLATZANZ, LEISTUNG, HUBRAUM, cast(trim(KZKAT) as blob(4k)) as KZKAT, cast(trim(KRAFTSTOFFART) as blob(4k)) as KRAFTSTOFFART, NOVA, cast(trim(AUFBAU) as blob(4k)) as AUFBAU, GAENGE, MODELLJAHR, EIGGEW, cast(trim(HAUPTCODE) as blob(4k)) as HAUPTCODE, cast(trim(STATCODE) as blob(4k)) as STATCODE, cast(trim(MOTORNR) as blob(4k)) as MOTORNR, cast(trim(FAHRGESTNR) as blob(4k)) as FAHRGESTNR, BAUARTGESCHW, cast(trim(FARBE) as blob(4k)) as FARBE, SONDERAUSST, NUTZLAST, NEUPREIS, ANMELDEDAT, ABMELDEDAT, ERSTZULDATUM, cast(trim(KZA9) as blob(4k)) as KZA9, A9DATUM, cast(trim(KFZZULBEH) as blob(4k)) as KFZZULBEH, cast(trim(KZEUROTAX) as blob(4k)) as KZEUROTAX, cast(trim(KFZKZ) as blob(4k)) as KFZKZ, cast(trim(KFZKZART) as blob(4k)) as KFZKZART, cast(trim(KFZKZLAND) as blob(4k)) as KFZKZLAND, KFZKZHINTERLBIS, KFZKZHINTERLAM, HOECHSTGESGEW, cast(trim(VBNR) as blob(4k)) as VBNR, JAHRVORZUL, A9DATBHEIN, A9DATBHBEARB, A9DATAUFHZUL, cast(trim(A9BEARBERG) as blob(4k)) as A9BEARBERG, A9RECHTDAT, cast(trim(ROLLE_BEZ2) as blob(4k)) as ROLLE_BEZ2, cast(trim(ZULASSUNGSID) as blob(4k)) as ZULASSUNGSID, cast(trim(GRUNDMATERIAL) as blob(4k)) as GRUNDMATERIAL, cast(trim(MOBIL) as blob(4k)) as MOBIL, SACH#, cast(trim(KZABS) as blob(4k)) as KZABS, cast(trim(KZESP) as blob(4k)) as KZESP, cast(trim(KZKFZALARM) as blob(4k)) as KZKFZALARM, cast(trim(MOTORART) as blob(4k)) as MOTORART, cast(trim(FZGKLASSE) as blob(4k)) as FZGKLASSE, CO2EMISSION, cast(trim(ENEFFKAT) as blob(4k)) as ENEFFKAT, SAISONPER_VON, SAISONPER_BIS, KFZ_LAENGE, KFZ_HOEHE, cast(trim(GETRIEBEART) as blob(4k)) as GETRIEBEART, CO2EMISSION_WLTP, ELECTRICAL_POWER, BATTERYPRICE)) body from TKFZ where SACH# in (select SACH# from VTSACHE)),
VTSACHORT as (select 'TSACHORT' as table_name, SACHORT#, XMLELEMENT(name "TSACHORT", XMLFOREST(SACHORT#, cast(trim(HAUSNR) as blob(4k)) as HAUSNR, cast(trim(HAUSNRZUS) as blob(4k)) as HAUSNRZUS, cast(trim(STIEGE) as blob(4k)) as STIEGE, cast(trim(TUERNR) as blob(4k)) as TUERNR, cast(trim(POSTFACH) as blob(4k)) as POSTFACH, cast(trim(POSTLANDSCHL) as blob(4k)) as POSTLANDSCHL, cast(trim(POSTLEITZAHL) as blob(4k)) as POSTLEITZAHL, cast(trim(GEMEINDEKZAHL) as blob(4k)) as GEMEINDEKZAHL, cast(ORTSCHAFT as blob(4k)) as ORTSCHAFT, cast(ORTSTEIL as blob(4k)) as ORTSTEIL, cast(trim(KZORTSTEILBED) as blob(4k)) as KZORTSTEILBED, cast(STRASSE as blob(4k)) as STRASSE, cast(trim(BDL_CODE) as blob(4k)) as BDL_CODE, cast(trim(GRUNDBUCHNR) as blob(4k)) as GRUNDBUCHNR, cast(trim(KZHORA) as blob(4k)) as KZHORA, cast(trim(KZGEPRADR) as blob(4k)) as KZGEPRADR, SACH#, cast(trim(STRASSE_TYP) as blob(4k)) as STRASSE_TYP, cast(BEZIRK as blob(4k)) as BEZIRK, cast(trim(KZADRUNSTRUKT) as blob(4k)) as KZADRUNSTRUKT, cast(trim(FLOOR) as blob(4k)) as FLOOR, cast(trim(POSTOFFICE) as blob(4k)) as POSTOFFICE)) body from TSACHORT where SACH# in (select SACH# from VTSACHE)),
--VTBN1_KFZ as (select 'TBN1_KFZ' as table_name, BN1_KFZ#, XMLELEMENT(name "TBN1_KFZ", XMLFOREST(BN1_KFZ#, cast(trim(BN1_DEDUCT_VAT) as blob(4k)) as BN1_DEDUCT_VAT, BN1_ACCELERATION, cast(trim(BN1_DRIVE) as blob(4k)) as BN1_DRIVE, cast(trim(BN1_TURBO) as blob(4k)) as BN1_TURBO, BN1_EXPECTMILEAGE, cast(trim(BN1_MELDCODE) as blob(4k)) as BN1_MELDCODE, cast(trim(BN1_ELECARPP) as blob(4k)) as BN1_ELECARPP, BN1_FIN_STRT_DAT, BN1_FIN_END_DAT, BN1_MANUFACTORDATE, BN1_NBS_DOORS, KFZ#, BN1_VALCONST, BN1_VALHHLUG, cast(trim(BN1_KZHAILROOF) as blob(4k)) as BN1_KZHAILROOF, BN1_POWERWEIGHT, cast(trim(BN1_UNIFIER) as blob(4k)) as BN1_UNIFIER, cast(trim(BN1_NEWPRICEDESC) as blob(4k)) as BN1_NEWPRICEDESC, cast(trim(BN1_MOTORMAKE) as blob(4k)) as BN1_MOTORMAKE, cast(trim(BN1_DIVCODE) as blob(4k)) as BN1_DIVCODE, cast(trim(BN1_SPORTSCAR) as blob(4k)) as BN1_SPORTSCAR, BN1_LASTREGDATE, BN1_WIDTH, cast(trim(BN1_MODCODE) as blob(4k)) as BN1_MODCODE, BN1_WINDRPLCCOST, BN1_REPAIRCOST, BN1_REPAIRRATIO, BN1_WRECKRATIO, BN1_SINISRATIO, cast(trim(BN1_SINISSEGMENT) as blob(4k)) as BN1_SINISSEGMENT, cast(trim(BN1_CLAIM12MONTHS) as blob(4k)) as BN1_CLAIM12MONTHS, cast(trim(BN1_CLAIM60DAYS) as blob(4k)) as BN1_CLAIM60DAYS, cast(trim(BN1_MILEAGEINCON) as blob(4k)) as BN1_MILEAGEINCON, cast(trim(BN1_TOTALLOSSRCRD) as blob(4k)) as BN1_TOTALLOSSRCRD, cast(trim(BN1_VEHICLECODEEU) as blob(4k)) as BN1_VEHICLECODEEU, cast(trim(BN1_CATALOGVALUE) as blob(4k)) as BN1_CATALOGVALUE, cast(trim(BN1_REGDATE) as blob(4k)) as BN1_REGDATE, cast(trim(BN1_FIRSTOWNER) as blob(4k)) as BN1_FIRSTOWNER, BN1_WHEELBASE, BN1_WRECKVALUE, BN1_KMPL)) body from TBN1_KFZ where KFZ# in (select KFZ# from VTKFZ)),
results as (
select table_name, body from VTVERTRAG
union all select table_name, body from VTANTRABW
--union all select table_name, body from VTBN1_LIAPREMPARAM
--union all select table_name, body from VTBN1_MOTPREMPARAM
--union all select table_name, body from VTBN1_PROPREMPARAM
--union all select table_name, body from VTBN1_VERTRAG
union all select table_name, body from VTGSCHFALL
union all select table_name, body from VTKLAGE
union all select table_name, body from VTKTOSTG
union all select table_name, body from VTPOLTXT_VERTR
union all select table_name, body from VTVEINDVER
union all select table_name, body from VTVERAENDSCHICHT
union all select table_name, body from VTVERSVERTRAG
union all select table_name, body from VTVERTR_SONSTROLL
union all select table_name, body from VTVERTRAG_GEN
union all select table_name, body from VTVERTRAUFWKTO
union all select table_name, body from VTVERTRBEZUG
union all select table_name, body from VTVERTRZUS
union all select table_name, body from VTVNEHMER
--union all select table_name, body from VTBN1_BMDETAILS
--union all select table_name, body from VTBN1_VERSVERTRAG
union all select table_name, body from VTBOMAAUSK
union all select table_name, body from VTINDIZIERUNG
union all select table_name, body from VTINDVER
union all select table_name, body from VTINDVORRUECKRECH
union all select table_name, body from VTPRODAUS
union all select table_name, body from VTPROVANSPRUCH
union all select table_name, body from VTSCHADEN
union all select table_name, body from VTSCHICHTPROT
union all select table_name, body from VTVERAENDSCHICHT_LZ
union all select table_name, body from VTVERSVERTRAG_GEN
union all select table_name, body from VTVINKGL
union all select table_name, body from VTVVZUABSCHLAG
union all select table_name, body from VTZUSKOSTEN
union all select table_name, body from VTBEZUGSRECHT
union all select table_name, body from VTEREIGNIS
union all select table_name, body from VTSCHICHTPROT_TUP
union all select table_name, body from VTTARIFGRUNDL
union all select table_name, body from VTTXTBWERTINH
union all select table_name, body from VTVERSPERS
union all select table_name, body from VTVERSSACHE
union all select table_name, body from VTSACHE
union all select table_name, body from VTBESITZVERH
union all select table_name, body from VTKFZ
union all select table_name, body from VTSACHORT
--union all select table_name, body from VTBN1_KFZ
)
SELECT xmlserialize(body as varchar(32000)) body FROM results;

--

with ttable as (
SELECT
'TVERTRAG' as table_name,
XMLELEMENT(name "TVERTRAG", XMLFOREST(v.VERTR#, v.POLLFNR)) body
FROM abs.TVERTRAG v where v.VERTR# = '8b0e084c-f739-11ee-9ebe-005056b2032c'
)
SELECT table_name,xmlserialize(body as varchar(32000)) body FROM ttable;

--TVERTRAG to BUSINESS PARTNER
select abs.timestampuuid(v.VERTR#),v.*, vz.*, f.*, j.*, p.*, bp.* 
from abs.TVERTRAG v
inner join abs.TVERTRZUS vz on v.VERTR# = vz.VERTR#
inner join abs.TFLOTTE f on f.FLOTTENNR = v.FLOTTENNR
inner join abs.TJURPERS j on f.JP# = j.JP#
inner join abs.TPERSON p on j.PERS# = p.PERS#
inner join abs.TGBPARTNER bp on p.PERS# = bp.PERS# and bp.GBPART = 'SEA'
--inner join abs.T
where vz.POLNR_VORSYS
like '%TEST713%' and v.STADIUM = '3' --and v.ZAHLWEISE = 'M' and

zus - zasw o niezaleganiu 2 131,73

560 16 00

--POSTGRES Sisyphos UPDATE
UPDATE contract set version =1,state = 'ERROR NO FIX',contract_json '{}',last_error = 'manual correction',last_error_at = '2024-07-10 13:00:00:000000' where state = 'VALIDATED'

--policy holder and insured person
SELECT * FROM abs.TVERTRAG v
join abs.TGSCHFALL g on v.GF# = g.GF#
join abs.TVERTRZUS z on v.VERTR# = z.VERTR#
--join abs.TVNEHMER ph on v.VERTR# = ph.VERTR#
join abs.TVERTR_SONSTROLL vs on v.VERTR# = vs.VERTR#
join abs.TADRESSE a on vs.PERS# = a.PERS#
where z.POLNR_VORSYSINT = '12LHHFB1601435222'


1600 brand - vehicle

something for recalc

Select substr(v.HPTFLLG,3,2), v.ABLDAT, v.ERNEUERART, ve.MO1_KZRECALC, v.ZAHLWEISE from abs.TVERTRAG v
inner join abs.TVERTRZUS vz on v.VERTR# = vz.VERTR#
inner join abs.TMO1_VERTRAG_ERW ve on v.VERTR# = ve.VERTR#
where vz.POLNR_VORSYSINT in 